// Code generated by `umbral gen-client`. DO NOT EDIT.
//
// Regenerate after any model or REST-resource change:
//     cargo run -- gen-client --out <this directory>
//
// A typed client for this app's REST API. Base path: /api
// Pagination: Custom. Auth: Bearer token / apiKey (X-API-Key). Row types live in ./models.ts.

import type { PaProduct, PaProductStatus } from "./models";
export * from "./models";

/** Filterable query parameters for `pa_product`. Every key is optional and AND-combined server-side. */
export interface PaProductFilters {
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
  "price"?: number;
  "price__ne"?: number;
  "price__gte"?: number;
  "price__lte"?: number;
  "price__gt"?: number;
  "price__lt"?: number;
  "price__in"?: number[];
  "in_stock"?: boolean;
  "in_stock__ne"?: boolean;
  "in_stock__in"?: boolean[];
  "blurb"?: string;
  "blurb__ne"?: string;
  "blurb__contains"?: string;
  "blurb__icontains"?: string;
  "blurb__startswith"?: string;
  "blurb__in"?: string[];
  "blurb__isnull"?: boolean;
  "status"?: PaProductStatus;
  "status__ne"?: PaProductStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: PaProductStatus[];
}
export type PaProductOrdering = "id" | "-id" | "name" | "-name" | "price" | "-price" | "in_stock" | "-in_stock" | "blurb" | "-blurb" | "status" | "-status";
/** Body for creating a `pa_product`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface PaProductCreate {
  name: string;
  price: number;
  in_stock: boolean;
  blurb?: string | null;
  status: PaProductStatus;
}
/** Body for updating a `pa_product` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface PaProductUpdate {
  name?: string;
  price?: number;
  in_stock?: boolean;
  blurb?: string | null;
  status?: PaProductStatus;
}

/** A list response, shaped to this API's paginator. */
export interface Paginated<T> {
  results: T[];
  next_cursor: string | null;
  prev_cursor: string | null;
  has_more: boolean;
}

/** Maps each REST-exposed table to its row, filter, and ordering types. `Umbral.from` keys off this. */
export interface UmbralResources {
  "pa_product": { row: PaProduct; filters: PaProductFilters; ordering: PaProductOrdering; create: PaProductCreate; update: PaProductUpdate; id: number };
}

export interface UmbralOptions {
  /** Token sent as `Bearer <token>` in the `Authorization` header
      (the prefix comes from your API's declared security scheme). Override the
      prefix with `tokenPrefix` — e.g. an API that expects `Token <key>`. */
  token?: string;
  /** Overrides the `Authorization` prefix for `token`. Defaults to
      "Bearer", read from the security scheme. */
  tokenPrefix?: string;
  /** API key sent in the `X-API-Key` header (the header name comes from
      your API's declared apiKey scheme). Override the header with
      `apiKeyHeader`. */
  apiKey?: string;
  /** Overrides the header `apiKey` is sent in. Defaults to "X-API-Key",
      read from the security scheme. */
  apiKeyHeader?: string;
  /** Dynamic auth: called per request, its headers merged in last (they win).
      Use for a rotating JWT, a refresh flow, request signing — anything the
      static options above can't express. */
  getAuthHeaders?: () => Record<string, string> | Promise<Record<string, string>>;
  /** Extra static headers merged into every request. */
  headers?: Record<string, string>;
  /** `fetch` credentials mode (cookies). Defaults to undefined. */
  credentials?: RequestCredentials;
  /** Custom fetch (SSR / tests). Defaults to the global `fetch`. */
  fetch?: typeof fetch;
  /** Base path of the realtime plugin, for `.on(...)`. Defaults to "/realtime". */
  realtimePath?: string;
}

/** A live subscription started by `Umbral.on`. Call `close()` to stop it. */
export interface Subscription {
  close(): void;
}

/** Handlers for model-change events. Each receives the row your `expose(...)`
    projection carries (the id by default), so you know which row to refetch. */
export interface ModelEvents<Row> {
  created?(row: Row): void;
  updated?(row: Row): void;
  deleted?(row: Row): void;
}

/** Thrown when the API returns a non-2xx response. `body` is the parsed error. */
export class UmbralError extends Error {
  constructor(public status: number, public body: unknown) {
    super(`umbral: request failed with status ${status}`);
    this.name = "UmbralError";
  }
}

class Query<Row, Filters, Ordering> {
  private params = new URLSearchParams();
  constructor(private client: Umbral, private table: string) {}

  /** Field filters — keys and value types are specific to this model. */
  filter(f: Filters): this {
    for (const [k, v] of Object.entries(f as Record<string, unknown>)) {
      if (v === undefined) continue;
      this.params.set(k, Array.isArray(v) ? v.join(",") : String(v));
    }
    return this;
  }

  /** Full-text `?search=` across the model's searchable columns. */
  search(term: string): this { this.params.set("search", term); return this; }

  /** `?ordering=` — pass fields; prefix `-` for descending. */
  orderBy(...fields: Ordering[]): this {
    this.params.set("ordering", (fields as unknown as string[]).join(","));
    return this;
  }

  /** Custom pagination param (`?cursor=`). */
  cursor(v: string): this { this.params.set("cursor", String(v)); return this; }
  /** Custom pagination param (`?page_size=`). */
  pageSize(v: number): this { this.params.set("page_size", String(v)); return this; }

  /** Set any raw query param — the escape hatch for params the typed builder
      methods don't cover (a custom paginator's cursor, a one-off flag). */
  param(key: string, value: string | number | boolean): this {
    this.params.set(key, String(value));
    return this;
  }

  /** Sparse fieldset (`?fields=`) — fetch only these columns. */
  fields(...cols: string[]): this { this.params.set("fields", cols.join(",")); return this; }

  /** Fetch the list. */
  async list(): Promise<Paginated<Row>> {
    const qs = this.params.toString();
    const path = `/api/${this.table}/` + (qs ? `?${qs}` : "");
    return this.client._request<Paginated<Row>>("GET", path);
  }
}

/** A typed client for this app's REST API. `new Umbral("https://api.example.com")`. */
export class Umbral {
  private realtimePath: string;
  constructor(private baseUrl: string, private opts: UmbralOptions = {}) {
    this.baseUrl = baseUrl.replace(/\/+$/, "");
    this.realtimePath = (opts.realtimePath ?? "/realtime").replace(/\/+$/, "");
  }

  /** Subscribe to `created` / `updated` / `deleted` events for a model over the
      realtime stream. The model must be `expose(...)`-d to `group` on the server.
      `"post"` autocompletes to exposed tables; each handler gets a typed row.
      Returns a {@link Subscription} — call `close()` to unsubscribe. */
  on<K extends keyof UmbralResources>(
    table: K,
    handlers: ModelEvents<Partial<UmbralResources[K]["row"]>>,
    opts: { group: string },
  ): Subscription {
    void table; // present for the type layer; the group carries the model's events
    const url =
      `${this.baseUrl}${this.realtimePath}/sse?groups=` + encodeURIComponent(opts.group);
    const es = new EventSource(url, { withCredentials: true });
    const onEvent = (ev: MessageEvent) => {
      let env: { c?: string; e?: string; d?: unknown };
      try { env = JSON.parse(ev.data); } catch { return; }
      if (env.c !== opts.group) return;
      const cb = (handlers as Record<string, ((row: unknown) => void) | undefined>)[env.e ?? ""];
      if (cb) cb(env.d);
    };
    es.addEventListener("u", onEvent as EventListener);
    return { close: () => es.close() };
  }

  /** Start a query against a REST-exposed table. */
  from<K extends keyof UmbralResources>(
    table: K,
  ): Query<UmbralResources[K]["row"], UmbralResources[K]["filters"], UmbralResources[K]["ordering"]> {
    return new Query(this, table as string);
  }

  /** Retrieve one row by primary key. */
  get<K extends keyof UmbralResources>(table: K, id: UmbralResources[K]["id"]): Promise<UmbralResources[K]["row"]> {
    return this._request(`GET`, `/api/${table as string}/${id}/`);
  }

  /** Create a row. The body type omits server-managed fields; `noedit` fields
      are allowed here (settable on create). */
  create<K extends keyof UmbralResources>(
    table: K,
    data: UmbralResources[K]["create"],
  ): Promise<UmbralResources[K]["row"]> {
    return this._request(`POST`, `/api/${table as string}/`, data);
  }

  /** Partially update a row (PATCH). The body type excludes `noedit` fields. */
  update<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
    data: UmbralResources[K]["update"],
  ): Promise<UmbralResources[K]["row"]> {
    return this._request(`PATCH`, `/api/${table as string}/${id}/`, data);
  }

  /** Delete a row by primary key. */
  async delete<K extends keyof UmbralResources>(table: K, id: UmbralResources[K]["id"]): Promise<void> {
    await this._request(`DELETE`, `/api/${table as string}/${id}/`);
  }

  /** @internal */
  async _request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const doFetch = this.opts.fetch ?? fetch;
    const headers: Record<string, string> = { "Accept": "application/json", ...this.opts.headers };
    // Auth, in ascending precedence: static token, static apiKey, then the
    // dynamic hook (so a fresh JWT overrides a stale static one). Defaults for
    // the prefix / header come from your API's declared security scheme.
    if (this.opts.token) {
      headers["Authorization"] = `${this.opts.tokenPrefix ?? "Bearer"} ${this.opts.token}`;
    }
    if (this.opts.apiKey) {
      headers[this.opts.apiKeyHeader ?? "X-API-Key"] = this.opts.apiKey;
    }
    if (this.opts.getAuthHeaders) {
      Object.assign(headers, await this.opts.getAuthHeaders());
    }
    const init: RequestInit = { method, headers };
    const credentials = this.opts.credentials ?? undefined;
    if (credentials) init.credentials = credentials;
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const res = await doFetch(this.baseUrl + path, init);
    const parsed = res.status === 204 ? null : await res.json().catch(() => null);
    if (!res.ok) throw new UmbralError(res.status, parsed);
    return parsed as T;
  }
}
