// Code generated by `umbral gen-client`. DO NOT EDIT.
//
// client.d.ts — the types
//
// Regenerate after any model or REST-resource change:
//     cargo run -- gen-client --out <this directory>
//
// Base path: /api. Auth: Bearer token / apiKey (X-API-Key).

// Code generated by `umbral typegen`. DO NOT EDIT.
//
// Regenerate after any model change:
//     cargo run -- typegen --out <this file>
//
// These describe the JSON umbral puts on the wire: the model struct as serde
// serialises it. Field names are snake_case because the wire is snake_case.
// A `ForeignKey<T>` is the target's primary-key value, not a nested object.

/** `draft` = Draft, `live` = Live */
export type PaProductStatus = "draft" | "live";

/** Table `pa_product`, from the `app` plugin. */
export interface PaProduct {
  id: number;
  name: string;
  price: number;
  in_stock: boolean;
  blurb: string | null;
  status: PaProductStatus;
}

/** Filterable query parameters for `pa_product`. Every key is optional and AND-combined server-side. */
export interface PaProductFilters {
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
  "price"?: number;
  "price__ne"?: number;
  "price__gte"?: number;
  "price__lte"?: number;
  "price__gt"?: number;
  "price__lt"?: number;
  "price__in"?: number[];
  "in_stock"?: boolean;
  "in_stock__ne"?: boolean;
  "in_stock__in"?: boolean[];
  "blurb"?: string;
  "blurb__ne"?: string;
  "blurb__contains"?: string;
  "blurb__icontains"?: string;
  "blurb__startswith"?: string;
  "blurb__in"?: string[];
  "blurb__isnull"?: boolean;
  "status"?: PaProductStatus;
  "status__ne"?: PaProductStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: PaProductStatus[];
}
export type PaProductOrdering = "id" | "-id" | "name" | "-name" | "price" | "-price" | "in_stock" | "-in_stock" | "blurb" | "-blurb" | "status" | "-status";
/** Body for creating a `pa_product`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface PaProductCreate {
  name: string;
  price: number;
  in_stock: boolean;
  blurb?: string | null;
  status: PaProductStatus;
}
/** Body for updating a `pa_product` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface PaProductUpdate {
  name?: string;
  price?: number;
  in_stock?: boolean;
  blurb?: string | null;
  status?: PaProductStatus;
}

/** A list response, shaped to this API's paginator. */
export interface Paginated<T> {
  results: T[];
  next_cursor: string | null;
  prev_cursor: string | null;
  has_more: boolean;
}

/** Maps each REST-exposed table to its row, filter, and ordering types. `Umbral.from` keys off this. */
export interface UmbralResources {
  "pa_product": { row: PaProduct; filters: PaProductFilters; ordering: PaProductOrdering; create: PaProductCreate; update: PaProductUpdate; id: number };
}

export interface UmbralOptions {
  /** Token sent as `Bearer <token>` in the `Authorization` header
      (the prefix comes from your API's declared security scheme). Override the
      prefix with `tokenPrefix` — e.g. an API that expects `Token <key>`. */
  token?: string;
  /** Overrides the `Authorization` prefix for `token`. Defaults to
      "Bearer", read from the security scheme. */
  tokenPrefix?: string;
  /** API key sent in the `X-API-Key` header (the header name comes from
      your API's declared apiKey scheme). Override with `apiKeyHeader`. */
  apiKey?: string;
  /** Overrides the header `apiKey` is sent in. Defaults to "X-API-Key",
      read from the security scheme. */
  apiKeyHeader?: string;
  /** Dynamic auth: called per request, its headers merged in last (they win).
      Use for a rotating JWT, a refresh flow, request signing — anything the
      static options above can't express. */
  getAuthHeaders?: () => Record<string, string> | Promise<Record<string, string>>;
  /** Extra static headers merged into every request. */
  headers?: Record<string, string>;
  /** `fetch` credentials mode (cookies). Defaults to undefined. */
  credentials?: RequestCredentials;
  /** Custom fetch (SSR / tests). Defaults to the global `fetch`. */
  fetch?: typeof fetch;
  /** Base path of the realtime plugin, for `.on(...)`. Defaults to "/realtime". */
  realtimePath?: string;
}

/** A live subscription started by `Umbral.on`. Call `close()` to stop it. */
export interface Subscription {
  close(): void;
}

/** Handlers for model-change events. Each receives the row your `expose(...)`
    projection carries (the id by default), so you know which row to refetch. */
export interface ModelEvents<Row> {
  created?(row: Row): void;
  updated?(row: Row): void;
  deleted?(row: Row): void;
}

/** Thrown when the API returns a non-2xx response. `body` is the parsed error. */
export declare class UmbralError extends Error {
  readonly status: number;
  readonly body: unknown;
  constructor(status: number, body: unknown);
}

/** A list query. Keys and value types are specific to the model it came from. */
export declare class Query<Row, Filters, Ordering> {
  /** Field filters — the keys are exactly the (field, lookup) pairs this model accepts. */
  filter(f: Filters): this;
  /** Full-text `?search=` across the model's searchable columns. */
  search(term: string): this;
  /** `?ordering=` — pass fields; prefix `-` for descending. */
  orderBy(...fields: Ordering[]): this;

  /** Custom pagination param (`?cursor=`). */
  cursor(v: string): this;

  /** Custom pagination param (`?page_size=`). */
  pageSize(v: number): this;

  /** Set any raw query param — the escape hatch for params the typed methods don't cover. */
  param(key: string, value: string | number | boolean): this;
  /** Sparse fieldset (`?fields=`) — fetch only these columns. */
  fields(...cols: string[]): this;
  /** Fetch the list. */
  list(): Promise<Paginated<Row>>;
}

/** A typed client for this app's REST API. */
export declare class Umbral {
  constructor(baseUrl: string, opts?: UmbralOptions);

  /** Start a query against a REST-exposed table. */
  from<K extends keyof UmbralResources>(
    table: K,
  ): Query<UmbralResources[K]["row"], UmbralResources[K]["filters"], UmbralResources[K]["ordering"]>;

  /** Retrieve one row by primary key. */
  get<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Create a row. The body type omits server-managed fields; `noedit` fields
      are allowed here (settable on create). */
  create<K extends keyof UmbralResources>(
    table: K,
    data: UmbralResources[K]["create"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Partially update a row (PATCH). The body type excludes `noedit` fields. */
  update<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
    data: UmbralResources[K]["update"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Delete a row by primary key. */
  delete<K extends keyof UmbralResources>(table: K, id: UmbralResources[K]["id"]): Promise<void>;

  /** Subscribe to `created` / `updated` / `deleted` for a model, over the
      realtime plugin's shared connection (one SSE stream across all tabs). The
      model must be `expose(...)`-d to `group` on the server. */
  on<K extends keyof UmbralResources>(
    table: K,
    handlers: ModelEvents<Partial<UmbralResources[K]["row"]>>,
    opts: { group: string },
  ): Subscription;
}
