//! SecurityReportsPlugin — generated by `umbra startapp security_reports`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(security_reports::SecurityReportsPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct SecurityReportsPlugin;

impl Plugin for SecurityReportsPlugin {
    fn name(&self) -> &'static str {
        "security_reports"
    }

    fn models(&self) -> Vec<umbra::migrate::ModelMeta> {
        // Register every model the plugin owns so makemigrations
        // picks them up. Uncomment + extend once you've defined one
        // in src/models.rs.
        // vec![umbra::migrate::ModelMeta::for_::<models::Example>()]
        Vec::new()
    }

    fn routes(&self) -> Router {
        // Add your routes here. The base path is up to you — convention
        // is `/<name>/...` for HTML and `/api/<name>/...` for JSON.
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
