//! ReviewsPlugin — generated by `umbra startapp reviews`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(reviews::ReviewsPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

pub use models::{Review, ReviewModeration, ReviewUsageContext};

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct ReviewsPlugin;

impl Plugin for ReviewsPlugin {
    fn name(&self) -> &'static str {
        "reviews"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![ModelMeta::for_::<models::Review>()]
    }

    fn routes(&self) -> Router {
        // Add your routes here. The base path is up to you — convention
        // is `/<name>/...` for HTML and `/api/<name>/...` for JSON.
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
