//! ContentPlugin — generated by `umbral startapp content`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(content::ContentPlugin::default())
//! ```

pub mod models;

pub use models::{
    Banner, Category, Comment, ContactMessage, Faq, MediaAsset, Menu, MenuItem, Note, Page, Post,
    Redirect, SiteSetting, Subscriber, Tag, Testimonial,
};

use umbral::migrate::ModelMeta;
use umbral::plugin::Plugin;

#[derive(Debug, Default, Clone)]
pub struct ContentPlugin;

impl Plugin for ContentPlugin {
    fn name(&self) -> &'static str {
        "content"
    }

    fn models(&self) -> Vec<ModelMeta> {
        // Every #[derive(Model)] in THIS crate, via the link-time registry
        // (gaps4 #40) — replaces 16 hand-listed ModelMeta::for_::<T>()
        // lines that had to be kept in sync with models.rs by hand.
        umbral::discovered_models!()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use umbral::plugin::Plugin;

    /// gaps4 #40 proof: every content model is discovered at link time.
    #[test]
    fn discovered_models_finds_all_sixteen() {
        let tables: std::collections::BTreeSet<String> = ContentPlugin
            .models()
            .into_iter()
            .map(|m| m.table)
            .collect();
        assert_eq!(
            tables.len(),
            16,
            "content owns 16 models; discovery found: {tables:?}"
        );
        assert!(tables.contains("post"));
        assert!(tables.contains("site_setting"));
    }
}
