//! ContentPlugin — generated by `umbra startapp content`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(content::ContentPlugin::default())
//! ```

pub mod models;

pub use models::{Category, Tag, Post, Comment, Page, Faq, Menu, MenuItem, Banner, Testimonial, ContactMessage, Note, Subscriber, MediaAsset, Redirect, SiteSetting};

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct ContentPlugin;

impl Plugin for ContentPlugin {
    fn name(&self) -> &'static str {
        "content"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![
            ModelMeta::for_::<models::Category>(),
            ModelMeta::for_::<models::Tag>(),
            ModelMeta::for_::<models::Post>(),
            ModelMeta::for_::<models::Comment>(),
            ModelMeta::for_::<models::Page>(),
            ModelMeta::for_::<models::Faq>(),
            ModelMeta::for_::<models::Menu>(),
            ModelMeta::for_::<models::MenuItem>(),
            ModelMeta::for_::<models::Banner>(),
            ModelMeta::for_::<models::Testimonial>(),
            ModelMeta::for_::<models::ContactMessage>(),
            ModelMeta::for_::<models::Note>(),
            ModelMeta::for_::<models::Subscriber>(),
            ModelMeta::for_::<models::MediaAsset>(),
            ModelMeta::for_::<models::Redirect>(),
            ModelMeta::for_::<models::SiteSetting>(),
        ]
    }

    fn routes(&self) -> Router {
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
