//! CommunityPlugin — generated by `umbra startapp community`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(community::CommunityPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

pub use models::{
    CommunityResource, CommunityResourceKind, NewsletterConfig, NewsletterProvider, SocialLink,
    SocialPlatform,
};

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct CommunityPlugin;

impl Plugin for CommunityPlugin {
    fn name(&self) -> &'static str {
        "community"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![
            ModelMeta::for_::<models::SocialLink>(),
            ModelMeta::for_::<models::CommunityResource>(),
            ModelMeta::for_::<models::NewsletterConfig>(),
        ]
    }

    fn routes(&self) -> Router {
        // Add your routes here. The base path is up to you — convention
        // is `/<name>/...` for HTML and `/api/<name>/...` for JSON.
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
