// Code generated by `umbral typegen`. DO NOT EDIT.
//
// Regenerate after any model change:
//     cargo run -- typegen --out <this file>
//
// These describe the JSON umbral puts on the wire: the model struct as serde
// serialises it. Field names are snake_case because the wire is snake_case.
// A `ForeignKey<T>` is the target's primary-key value, not a nested object.

/** `draft` = Draft, `live` = Live */
export type PaProductStatus = "draft" | "live";

/** Table `pa_product`, from the `app` plugin. */
export interface PaProduct {
  id: number;
  name: string;
  price: number;
  in_stock: boolean;
  blurb: string | null;
  status: PaProductStatus;
}
