//! PublicPlugin - generated by `umbra startapp public`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(public::PublicPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

use std::path::PathBuf;

use umbra::routes::RouteSpec;
use umbra::templates::context;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::{Html, Router, StatusCode, get};

#[derive(Debug, Default, Clone)]
pub struct PublicPlugin;

impl Plugin for PublicPlugin {
    fn name(&self) -> &'static str {
        "public"
    }

    fn models(&self) -> Vec<umbra::migrate::ModelMeta> {
        // Register every model the plugin owns so makemigrations
        // picks them up. Uncomment + extend once you've defined one
        // in src/models.rs.
        // vec![umbra::migrate::ModelMeta::for_::<models::Example>()]
        Vec::new()
    }

    fn routes(&self) -> Router {
        Router::new().route("/", get(home))
    }

    fn route_paths(&self) -> Vec<RouteSpec> {
        vec![RouteSpec::new("/", vec!["GET"])]
    }

    fn templates_dirs(&self) -> Vec<PathBuf> {
        vec![PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("templates")]
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}

async fn home() -> Result<Html<String>, (StatusCode, String)> {
    let body = umbra::templates::render("public/home.html", &context!())
        .map_err(internal_error)?;
    Ok(Html(body))
}

fn internal_error<E: std::fmt::Display>(err: E) -> (StatusCode, String) {
    (StatusCode::INTERNAL_SERVER_ERROR, err.to_string())
}
