//! shop — generated by `umbra startproject shop`.
//!
//! Full e-commerce + content example app. Wires auth, sessions, permissions,
//! admin, REST with filters, content plugin, and ecommerce plugin.
//!
//! Run with:
//!   cargo run -- migrate   # apply pending migrations
//!   cargo run -- serve     # boot the HTTP server
//!   cargo run -- makemigrations
//!   cargo run -- showmigrations
//!   cargo run -- createsuperuser

mod auth;

use std::sync::Arc;

use content::ContentPlugin;
use ecommerce::EcommercePlugin;
use umbra::migrate::MigrateError;
use umbra::prelude::*;
use umbra::templates::context;
use umbra::web::{Html, Path, SlashRedirect, StatusCode};
use umbra_admin::{AdminModel, AdminPlugin};
use umbra_auth::{AuthPlugin, AuthUser, BearerAuthentication, UserModel, login_required_html};
use umbra_openapi::OpenApiPlugin;
use umbra_permissions::{PermissionsPlugin, permission_required_html};
use umbra_playground::PlaygroundPlugin;
use umbra_rest::{
    Authentication, ChainAuthentication, IsAuthenticated, IsStaff, OrPermission,
    PageNumberPagination, ReadOnly, ResourceConfig, RestPlugin,
};
use umbra_sessions::SessionsPlugin;

use crate::auth::{TokenSchemeAuthentication, session_authentication};

use content::models::{Category, Comment, Faq, Post, PostStatus, Tag, Testimonial};
use ecommerce::models::{
    AddressType, Brand, Coupon, Currency, Customer, DiscountType, Order, OrderItem, OrderStatus,
    Payment, PaymentMethod, PaymentStatus, Product, ProductStatus, Review, Shipment, brand,
    customer, product,
};
// The cross-crate reverse-OneToOne accessor trait — gives
// AuthUser the `customer().await?` method even though Customer
// lives in the ecommerce crate. Imported here so the /me handler
// below can call `user.customer().await?` directly. The trait
// itself was emitted by `#[derive(Model)]` on Customer, picked up
// because of the `OneToOne<AuthUser>` field shape.
use ecommerce::models::CustomerUserOneToOneReverse;

// ---------------------------------------------------------------------------
// App wiring
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let settings = Settings::from_env()?;
    let pool = umbra::db::connect(&settings.database_url).await?;

    let app = App::builder()
        .settings(settings)
        .database("default", pool)
        // --- Plugins ---------------------------------------------------------
        .plugin(AuthPlugin::<AuthUser>::default().with_default_routes())
        .plugin(SessionsPlugin::default())
        .plugin(PermissionsPlugin)
        .plugin(ContentPlugin)
        .plugin(EcommercePlugin)
        // Admin: declare per-model search + filter columns on the
        // ecommerce side so the changelist toolbar shows the search
        // input + Filter button. `register_for("ecommerce", ...)` keeps
        // the sidebar grouping AND the per-model permission codenames
        // (`ecommerce.view_product`, etc.) aligned with the plugin
        // that owns each model. Auto-discovered models without an
        // explicit AdminModel keep their defaults — empty list_filter
        // and empty search_fields hide the toolbar controls, which is
        // the intended behaviour when nothing is declared.
        .plugin(
            AdminPlugin::default()
                .site_title("Shop".to_string())
                .register_for(
                    "ecommerce",
                    AdminModel::new("product")
                        .search_fields(&["name", "sku", "slug"])
                        .list_filter(&["status", "category", "brand", "is_featured", "currency"]),
                )
                .register_for(
                    "ecommerce",
                    AdminModel::new("brand").search_fields(&["name", "slug"]),
                )
                .register_for(
                    "ecommerce",
                    AdminModel::new("order")
                        .search_fields(&["number"])
                        .list_filter(&["status", "payment_status", "currency"]),
                )
                .register(
                    umbra_admin::AdminModel::new("auth_user")
                        .label("Users")
                        .icon("users")
                        .password_field("password_hash"),
                )
                // Dashboard layout — named sections beat one
                // mega-grid as widget count grows. Each section
                // gets a title + optional subtitle + its own
                // widget grid below the heading.
                //
                // Model-cards section also gets a humanized title
                // ("Data") and a subtitle. Curated allowlist via
                // the type-safe `models![T, U, V]` macro — renames
                // propagate without chasing strings.
                .dashboard_models_title("Data")
                .dashboard_models_subtitle("Jump straight to a managed table")
                .dashboard_models_only(&umbra::models![
                    ecommerce::models::Product,
                    ecommerce::models::Order,
                    ecommerce::models::Customer,
                    ecommerce::models::Brand,
                    ecommerce::models::Coupon,
                    content::models::Post,
                ])
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Sales overview")
                        .subtitle("Daily KPIs across the storefront")
                        .widget(shop_total_sales_widget())
                        .widget(shop_orders_widget())
                        .widget(shop_customers_widget())
                        .widget(shop_avg_order_value_widget()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Trends")
                        .subtitle("Daily sales + multi-series activity + status mix + recent orders")
                        .widget(shop_daily_sales_chart())
                        .widget(shop_activity_chart())
                        .widget(shop_order_status_donut())
                        .widget(shop_recent_orders_table()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("System")
                        .subtitle("Framework-wide health + recent activity")
                        .widget(
                            umbra_admin::builtin_total_models_widget().with_span(8, 2),
                        )
                        .widget(
                            umbra_admin::builtin_recent_users_widget().with_span(4, 2),
                        ),
                ),
        )
        // REST: three resources, three different auth + permission
        // postures, plus per-resource field-exposure controls. The
        // global authenticator is a CHAIN — try session first (browsers
        // get cookies), then Bearer, then the custom `Token <T>`
        // scheme. Whichever matches yields the same Identity shape; the
        // per-resource Permission decides what they can do.
        .plugin(
            RestPlugin::default()
                .paginate(PageNumberPagination::new(20))
                .authenticate(ChainAuthentication::new(vec![
                    Arc::new(session_authentication()) as Arc<dyn Authentication>,
                    Arc::new(BearerAuthentication::default()) as Arc<dyn Authentication>,
                    Arc::new(TokenSchemeAuthentication::default()) as Arc<dyn Authentication>,
                ]))
                // product: anyone can read, only staff can write.
                // `cost` is internal margin data — never leaks out.
                // Combined with #[umbra(noform)] / noedit on the model
                // this would also lock the field on the write path.
                .resource(ResourceConfig::new("product").hide("cost").permission(
                    OrPermission::new(vec![Box::new(ReadOnly), Box::new(IsStaff)]),
                ))
                // order: every action requires an authenticated caller
                // (the cookie path is the realistic one for a real
                // shop; bearer / token are convenient for curl smoke
                // testing).
                .resource(ResourceConfig::new("order").permission(IsAuthenticated))
                // post: same public-read + staff-write shape as
                // product. Demonstrates the *custom* Token scheme:
                // POST /api/post/ with `Authorization: Token <key>`
                // lands here through the chain authenticator.
                .resource(
                    ResourceConfig::new("post").permission(OrPermission::new(vec![
                        Box::new(ReadOnly),
                        Box::new(IsStaff),
                    ])),
                ),
        )
        .plugin(OpenApiPlugin::new())
        .plugin(PlaygroundPlugin::new("shop"))
        // --- Templates -------------------------------------------------------
        .templates_dir("templates")
        .not_found_template("404.html")
        .server_error_template("500.html")
        .slash_redirect(SlashRedirect::Append)
        // --- Routes ----------------------------------------------------------
        .routes(
            Routes::new()
                .get("/", home)
                .get("/products", product_list)
                .get("/products/{id}", product_detail)
                .layered(
                    "GET",
                    "/dashboard",
                    get(dashboard).layer(login_required_html("/login")),
                )
                .layered(
                    "GET",
                    "/staff-only",
                    get(staff_only)
                        .layer(permission_required_html("ecommerce.view_product", "/login")),
                )
                .layered("GET", "/me", get(me).layer(login_required_html("/login"))),
        )
        .build()?;

    let explained_query = Product::objects()
        // .only(&["id"])
        .only(&["id", "name", "category__name"])
        .join_related("category")
        .filter(product::ID.eq(1))
        // .select_related("category")
        .to_sql();
    eprintln!("explain: {}", explained_query);

    if is_serve_invocation() {
        auto_migrate().await?;
        // Order matters:
        //  1. test_credentials creates the shopadmin user (id=1).
        //  2. products gives demo_data products to link orders to.
        //  3. demo_data creates extra users (alice/bob/carol → 2,3,4)
        //     so that step (4) can attach blog comments to them.
        //  4. blogs uses those users as comment authors.
        seed_test_credentials().await?;
        seed_products().await?;
        seed_demo_data().await?;
        seed_blogs().await?;
    }

    umbra_cli::dispatch(app).await
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

async fn home() -> Result<Html<String>, (StatusCode, String)> {
    let featured = Product::objects()
        .filter(product::IS_FEATURED.eq(true))
        .filter(product::STATUS.eq("active"))
        .order_by(product::CREATED_AT.desc())
        .limit(4)
        .fetch()
        .await
        .map_err(internal_error)?;

    let brands = Brand::objects()
        .order_by(brand::NAME.asc())
        .fetch()
        .await
        .map_err(internal_error)?;

    let body = umbra::templates::render("home.html", &context!(featured, brands))
        .map_err(internal_error)?;
    Ok(Html(body))
}

async fn product_list() -> Result<Html<String>, (StatusCode, String)> {
    let products = Product::objects()
        .filter(product::STATUS.eq("active"))
        .order_by(product::NAME.asc())
        .fetch()
        .await
        .map_err(internal_error)?;

    let body = umbra::templates::render("product_list.html", &context!(products))
        .map_err(internal_error)?;
    Ok(Html(body))
}

async fn product_detail(Path(id): Path<i64>) -> Result<Html<String>, (StatusCode, String)> {
    let product = Product::objects()
        .filter(product::ID.eq(id))
        .first()
        .await
        .map_err(internal_error)?
        .ok_or_else(|| (StatusCode::NOT_FOUND, format!("Product {id} not found")))?;

    let body = umbra::templates::render("product_detail.html", &context!(product))
        .map_err(internal_error)?;
    Ok(Html(body))
}

async fn dashboard(
    user: umbra_auth::LoggedIn<AuthUser>,
) -> Result<Html<String>, (StatusCode, String)> {
    let username = user.0.username().to_string();
    let body =
        umbra::templates::render("dashboard.html", &context!(username)).map_err(internal_error)?;
    Ok(Html(body))
}

async fn staff_only() -> Result<Html<String>, (StatusCode, String)> {
    let body = umbra::templates::render("staff_only.html", &context!()).map_err(internal_error)?;
    Ok(Html(body))
}

/// Exercise the cross-crate reverse-OneToOne accessor end-to-end.
/// `user.customer().await?` is the trait method emitted by
/// `#[derive(Model)]` on Customer because of the `OneToOne<AuthUser>`
/// field. AuthUser lives in `umbra-auth`; Customer lives in
/// `examples/shop/plugins/ecommerce` — the accessor still resolves
/// thanks to the trait-on-foreign-type emission (mirror of the
/// gap #105 reverse-FK fix).
///
/// Plain-text response keeps the demo focused on the relationship
/// walk, no template engine in the way.
async fn me(user: umbra_auth::LoggedIn<AuthUser>) -> Result<Html<String>, (StatusCode, String)> {
    let username = user.0.username().to_string();
    let user_id = user.0.id;

    // THE NEW THING — cross-crate parent → child accessor.
    let customer = user.0.customer().await.map_err(internal_error)?;

    let body = match customer {
        Some(c) => format!(
            "<!doctype html><h1>{username}</h1>\
             <p><strong>AuthUser id</strong>: {user_id} (umbra-auth crate)</p>\
             <p><strong>Customer id</strong>: {} (ecommerce crate)</p>\
             <p><strong>Loyalty points</strong>: {}</p>\
             <p>Loaded via <code>user.customer().await?</code> — the cross-crate \
             reverse-O2O accessor.</p>\
             <p><a href='/admin'>Admin</a></p>",
            c.id, c.loyalty_points,
        ),
        None => format!(
            "<!doctype html><h1>{username}</h1>\
             <p>AuthUser id {user_id} has no Customer row — \
             <code>user.customer().await?</code> returned <code>None</code>.</p>\
             <p><a href='/admin'>Admin</a></p>"
        ),
    };
    Ok(Html(body))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn internal_error<E: std::fmt::Display>(err: E) -> (StatusCode, String) {
    (StatusCode::INTERNAL_SERVER_ERROR, err.to_string())
}

fn is_serve_invocation() -> bool {
    matches!(std::env::args().nth(1).as_deref(), None | Some("serve"))
}

async fn auto_migrate() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    match umbra::migrate::make().await {
        Ok(paths) => {
            for path in paths {
                eprintln!("auto-migrate: wrote {}", path.display());
            }
        }
        Err(MigrateError::NoChanges) => {}
        Err(err) => return Err(Box::new(err)),
    }
    let n = umbra::migrate::run().await?;
    if n > 0 {
        eprintln!("auto-migrate: applied {n} migration(s)");
    }
    Ok(())
}

/// First-run convenience for gap #82 manual testing: when no users
/// exist yet, mint a deterministic superuser ("shopadmin" /
/// "shopadmin") plus a bearer token, and print both to stderr so
/// the developer can curl the gated endpoints without leaving the
/// terminal. Idempotent — subsequent boots find the user, skip the
/// create, and stay quiet.
///
/// NEVER ship this in production. It's a test scaffold; production
/// would call `createsuperuser` interactively.
async fn seed_test_credentials() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    use umbra_auth::AuthUser;
    use umbra_auth::token::AuthToken;

    if AuthUser::objects().count().await? > 0 {
        return Ok(());
    }

    let user = umbra_auth::create_superuser("shopadmin", "shopadmin@example.com", "shopadmin")
        .await
        .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;
    let (_row, token) = AuthToken::create_for(&user, "shop-demo")
        .await
        .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;

    eprintln!();
    eprintln!("======================================================================");
    eprintln!(" TEST CREDENTIALS — seeded because no users existed yet (gap #82)");
    eprintln!("----------------------------------------------------------------------");
    eprintln!(" Username : shopadmin");
    eprintln!(" Password : shopadmin");
    eprintln!(" Token    : {token}");
    eprintln!();
    eprintln!(" Try a public read (no auth):");
    eprintln!("   curl -s http://localhost:8000/api/product/?fields=id,name,price | jq");
    eprintln!();
    eprintln!(" Try a Bearer-gated write:");
    eprintln!("   curl -X DELETE -H 'Authorization: Bearer {token}' \\");
    eprintln!("        http://localhost:8000/api/product/1");
    eprintln!();
    eprintln!(" Try the CUSTOM `Token` scheme on a blog post:");
    eprintln!("   curl -X DELETE -H 'Authorization: Token {token}' \\");
    eprintln!("        http://localhost:8000/api/post/1");
    eprintln!();
    eprintln!(" Try anonymous write (expect 401):");
    eprintln!("   curl -X DELETE http://localhost:8000/api/product/1");
    eprintln!();
    eprintln!(" Try order (any auth required, even read):");
    eprintln!("   curl -H 'Authorization: Bearer {token}' \\");
    eprintln!("        http://localhost:8000/api/order/");
    eprintln!("======================================================================");
    eprintln!();

    Ok(())
}

async fn seed_products() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // Seed categories if empty
    if Category::objects().count().await? == 0 {
        Category::objects()
            .bulk_create(vec![
                Category {
                    id: 0,
                    slug: "gadgets".into(),
                    name: "Gadgets".into(),
                    description: Some("Tech and gadgets".into()),
                    image: None,
                    parent: None,
                    position: 0,
                    is_active: true,
                    test_field: None,
                },
                Category {
                    id: 0,
                    slug: "home".into(),
                    name: "Home & Living".into(),
                    description: Some("Home goods".into()),
                    image: None,
                    parent: None,
                    position: 1,
                    is_active: true,
                    test_field: None,
                },
            ])
            .await?;
    }

    // Seed brands if empty
    if Brand::objects().count().await? == 0 {
        Brand::objects()
            .bulk_create(vec![
                Brand {
                    id: 0,
                    name: "Acme Corp".into(),
                    slug: "acme-corp".into(),
                    logo: None,
                    website: None,
                    description: Some("Quality gadgets since 1920".into()),
                },
                Brand {
                    id: 0,
                    name: "UmbraGear".into(),
                    slug: "umbragear".into(),
                    logo: None,
                    website: None,
                    description: Some("Tools for developers".into()),
                },
                Brand {
                    id: 0,
                    name: "Rustic".into(),
                    slug: "rustic".into(),
                    logo: None,
                    website: None,
                    description: Some("Handcrafted home goods".into()),
                },
            ])
            .await?;
    }

    // Seed products if empty
    if Product::objects().count().await? == 0 {
        let brands = Brand::objects().fetch().await?;
        let brand_fk = brands.first().map(|b| ForeignKey::new(b.id));

        Product::objects()
            .bulk_create(vec![
                Product {
                    id: 0,
                    sku: "ACM-001".into(),
                    slug: "acme-widget".into(),
                    name: "Acme Widget".into(),
                    description: "The original, the classic. A must-have for any gadget enthusiast.".into(),
                    status: ProductStatus::Active,
                    category: ForeignKey::new(1),
                    brand: brand_fk.clone(),
                    price: "29.99".into(),
                    compare_at_price: None,
                    cost: "15.00".into(),
                    currency: Currency::Usd,
                    tax_rate: "0.00".into(),
                    stock_quantity: 100,
                    weight_kg: Some(0.5),
                    dimensions: None,
                    barcode: None,
                    thumbnail: None,
                    spec_sheet: None,
                    is_featured: true,
                    rating_avg: 0.0,
                    review_count: 0,
                    metadata: serde_json::json!({}),
                    keywords: None,
                    external_id: None,
                    published_at: Some(chrono::Utc::now()),
                    created_at: chrono::Utc::now(),
                    updated_at: chrono::Utc::now(),
                },
                Product {
                    id: 0,
                    sku: "UGR-101".into(),
                    slug: "developer-keyboard".into(),
                    name: "Mechanical Dev Keyboard".into(),
                    description: "Clicky switches, RGB lighting, and a Rust logo on the spacebar.".into(),
                    status: ProductStatus::Active,
                    category: ForeignKey::new(1),
                    brand: brand_fk.clone(),
                    price: "149.00".into(),
                    compare_at_price: Some("199.00".into()),
                    cost: "80.00".into(),
                    currency: Currency::Usd,
                    tax_rate: "0.00".into(),
                    stock_quantity: 45,
                    weight_kg: Some(1.2),
                    dimensions: None,
                    barcode: None,
                    thumbnail: None,
                    spec_sheet: None,
                    is_featured: true,
                    rating_avg: 0.0,
                    review_count: 0,
                    metadata: serde_json::json!({}),
                    keywords: None,
                    external_id: None,
                    published_at: Some(chrono::Utc::now()),
                    created_at: chrono::Utc::now(),
                    updated_at: chrono::Utc::now(),
                },
                Product {
                    id: 0,
                    sku: "RUS-777".into(),
                    slug: "rustic-coffee-mug".into(),
                    name: "Rustic Coffee Mug".into(),
                    description: "Hand-thrown ceramic mug with a warm glaze. Holds 12oz of your favourite brew.".into(),
                    status: ProductStatus::Active,
                    category: ForeignKey::new(1),
                    brand: brand_fk.clone(),
                    price: "24.00".into(),
                    compare_at_price: None,
                    cost: "8.00".into(),
                    currency: Currency::Usd,
                    tax_rate: "0.00".into(),
                    stock_quantity: 200,
                    weight_kg: Some(0.4),
                    dimensions: None,
                    barcode: None,
                    thumbnail: None,
                    spec_sheet: None,
                    is_featured: false,
                    rating_avg: 0.0,
                    review_count: 0,
                    metadata: serde_json::json!({}),
                    keywords: None,
                    external_id: None,
                    published_at: Some(chrono::Utc::now()),
                    created_at: chrono::Utc::now(),
                    updated_at: chrono::Utc::now(),
                },
            ])
            .await?;
    }

    Ok(())
}

async fn seed_blogs() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // Seed tags if empty
    if Tag::objects().count().await? == 0 {
        Tag::objects()
            .bulk_create(vec![
                Tag {
                    id: 0,
                    name: "Rust".into(),
                    slug: "rust".into(),
                },
                Tag {
                    id: 0,
                    name: "Web Development".into(),
                    slug: "web-development".into(),
                },
                Tag {
                    id: 0,
                    name: "Database".into(),
                    slug: "database".into(),
                },
                Tag {
                    id: 0,
                    name: "Performance".into(),
                    slug: "performance".into(),
                },
                Tag {
                    id: 0,
                    name: "Architecture".into(),
                    slug: "architecture".into(),
                },
                Tag {
                    id: 0,
                    name: "API Design".into(),
                    slug: "api-design".into(),
                },
                Tag {
                    id: 0,
                    name: "Security".into(),
                    slug: "security".into(),
                },
                Tag {
                    id: 0,
                    name: "DevOps".into(),
                    slug: "devops".into(),
                },
            ])
            .await?;
    }

    // Seed posts if empty
    if Post::objects().count().await? == 0 {
        let now = chrono::Utc::now();
        let author = ForeignKey::new(1); // admin user
        let category = ForeignKey::new(1); // gadgets category

        let posts = vec![
            heavy_post(
                1,
                "building-high-performance-apis-in-rust",
                "Building High-Performance APIs in Rust",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                2,
                "understanding-database-indexes",
                "Understanding Database Indexes: A Deep Dive",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                3,
                "async-rust-patterns",
                "Async Rust Patterns for Production Systems",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                4,
                "zero-copy-serialization",
                "Zero-Copy Serialization Techniques",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                5,
                "web-framework-design-principles",
                "Web Framework Design Principles",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                6,
                "memory-management-in-systems-programming",
                "Memory Management in Systems Programming",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                7,
                "scaling-sqlite-to-millions-of-rows",
                "Scaling SQLite to Millions of Rows",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                8,
                "postgres-query-optimization",
                "PostgreSQL Query Optimization Strategies",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                9,
                "rust-ownership-model-explained",
                "The Rust Ownership Model Explained",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                10,
                "building-django-like-frameworks",
                "Building Django-Like Frameworks in Rust",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                11,
                "concurrency-patterns-in-modern-web-servers",
                "Concurrency Patterns in Modern Web Servers",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                12,
                "type-safe-database-migrations",
                "Type-Safe Database Migrations",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                13,
                "rest-api-versioning-strategies",
                "REST API Versioning Strategies",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                14,
                "caching-strategies-for-web-applications",
                "Caching Strategies for Web Applications",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                15,
                "securing-web-applications-owasp-top-ten",
                "Securing Web Applications: OWASP Top Ten",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                16,
                "microservices-vs-monoliths",
                "Microservices vs Monoliths: A Practical Guide",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                17,
                "real-time-data-processing",
                "Real-Time Data Processing with Rust",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                18,
                "error-handling-in-distributed-systems",
                "Error Handling in Distributed Systems",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                19,
                "load-testing-and-benchmarking",
                "Load Testing and Benchmarking Web APIs",
                &author,
                &category,
                &now,
            ),
            heavy_post(
                20,
                "future-of-web-development",
                "The Future of Web Development: 2026 and Beyond",
                &author,
                &category,
                &now,
            ),
        ];

        Post::objects().bulk_create(posts).await?;

        // Seed comments on the first 10 posts
        let comment_posts = Post::objects().limit(10).fetch().await?;
        let mut comments = vec![];
        for post in &comment_posts {
            comments.push(Comment {
                id: 0,
                post: ForeignKey::new(post.id),
                parent: None,
                author: Some(ForeignKey::new(2)),
                author_name: None,
                author_email: None,
                body: "This is exactly what I was looking for. The explanation of the core concepts really helped clarify things for our team. We ended up adopting several of the patterns described here and saw immediate improvements in our codebase.".into(),
                is_approved: true,
                created_at: now,
            });
            comments.push(Comment {
                id: 0,
                post: ForeignKey::new(post.id),
                parent: None,
                author: Some(ForeignKey::new(3)),
                author_name: None,
                author_email: None,
                body: "Great article! I would love to see a follow-up covering the edge cases we ran into when implementing this at scale. Specifically, how do you handle backpressure when the system is under heavy load?".into(),
                is_approved: true,
                created_at: now,
            });
            comments.push(Comment {
                id: 0,
                post: ForeignKey::new(post.id),
                parent: None,
                author: None,
                author_name: Some("Guest Reader".into()),
                author_email: Some("guest@example.com".into()),
                body: "Thanks for writing this. It saved me hours of research. The benchmarks comparing different approaches were particularly valuable.".into(),
                is_approved: true,
                created_at: now,
            });
        }
        if !comments.is_empty() {
            Comment::objects().bulk_create(comments).await?;
        }
    }

    Ok(())
}

fn heavy_post(
    idx: i64,
    slug: &str,
    title: &str,
    author: &ForeignKey<umbra_auth::AuthUser>,
    category: &ForeignKey<Category>,
    now: &chrono::DateTime<chrono::Utc>,
) -> Post {
    let body = format!(
        r#"<h2>Introduction</h2>
<p>Welcome to our comprehensive guide on {}. In this article, we will explore the fundamental concepts, practical implementations, and advanced techniques that have emerged from years of production experience. Whether you are a seasoned developer or just getting started, there is something here for everyone.</p>

<h2>The Problem Space</h2>
<p>When building modern web applications, developers face a unique set of challenges. Systems must handle thousands of concurrent connections while maintaining sub-millisecond response times. Data consistency across distributed nodes becomes non-trivial. Security threats evolve faster than most teams can patch. And perhaps most importantly, the codebase must remain maintainable as the team grows.</p>

<p>Consider a typical e-commerce platform. On any given day, it processes hundreds of thousands of transactions, each touching inventory, payment, shipping, and notification subsystems. A failure in any one component cascades rapidly. The database layer must absorb massive read spikes during flash sales. The API layer must validate every request against sophisticated fraud rules. And all of this must happen while the site remains responsive to browsing customers.</p>

<h2>Core Concepts</h2>
<p>At the heart of any robust solution lies a set of well-understood primitives. First, <strong>ownership and borrowing</strong> ensure that memory is managed without garbage collection pauses. Second, <strong>zero-cost abstractions</strong> let us express high-level intent without runtime overhead. Third, <strong>composability</strong> means we can build complex systems from simple, tested components.</p>

<p>Let us look at a concrete example. Imagine we need to process a stream of incoming orders. In a traditional approach, we might spin up a thread per connection. At low volumes this works fine. But as concurrency increases, context switching dominates CPU time and memory pressure mounts. The modern approach uses asynchronous I/O with a small pool of executor threads. Each connection is represented as a lightweight future, scheduled cooperatively rather than preemptively.</p>

<h2>Implementation Strategies</h2>
<p>There are three primary strategies we have seen succeed in production:</p>
<ol>
<li><strong>Connection pooling:</strong> Reuse expensive TCP and TLS handshakes across requests. A well-tuned pool keeps a small warm set of connections ready, scaling up under load and down during idle periods.</li>
<li><strong>Request batching:</strong> Group small reads into larger multi-row queries. This reduces round-trips and lets the database optimizer do more effective work per query.</li>
<li><strong>Circuit breakers:</strong> When a downstream service fails, stop sending it traffic temporarily. This prevents cascading failures and gives the dependency time to recover.</li>
</ol>

<p>Implementing these requires careful attention to observability. Every pool, batch, and breaker should emit metrics: queue depth, latency percentiles, error rates. Without visibility, tuning becomes guesswork.</p>

<h2>Benchmarks and Results</h2>
<p>We ran a series of benchmarks on a standard cloud instance (4 vCPU, 16 GB RAM). The baseline, unoptimized service handled 2,400 requests per second at p99 latency of 45ms. After applying the strategies above, throughput increased to 18,000 requests per second with p99 latency of 8ms. That is a 7.5x throughput improvement and a 5.6x latency reduction.</p>

<p>Breaking down the wins: connection pooling contributed roughly 2x, batching another 2.5x, and circuit breakers prevented the occasional latency spike that previously dragged the p99 up. The remaining improvement came from removing unnecessary serialization round-trips.</p>

<h2>Common Pitfalls</h2>
<p>Even experienced teams stumble. The most common mistake is over-optimizing too early. We have seen teams implement elaborate caching layers before they understand their actual access patterns. The result is complex invalidation logic, stale data bugs, and minimal performance gain because the cache hit rate is low.</p>

<p>Another frequent error is ignoring backpressure. When the system cannot keep up, it should shed load gracefully rather than queue indefinitely. Unbounded queues masquerade as healthy systems right up until they exhaust memory and crash.</p>

<h2>Future Directions</h2>
<p>The ecosystem continues to evolve. WebAssembly is opening new deployment models. Edge computing is pushing logic closer to users. And advances in database internals are making previously impractical query patterns feasible.</p>

<p>We are particularly excited about compile-time checked SQL, which eliminates an entire class of runtime errors. And the growing maturity of async runtimes means we can write straightforward code that compiles to highly efficient state machines.</p>

<h2>Conclusion</h2>
<p>Building high-performance systems is less about raw speed and more about understanding trade-offs. Every optimization has a cost: complexity, maintainability, or both. The best engineers choose their battles carefully, instrument everything, and validate assumptions with real data.</p>

<p>We hope this guide has given you a solid foundation. The techniques described here have served us well across multiple projects and teams. As always, the code is available in our repository. Pull requests and issue reports are welcome.</p>

<p><em>This is post number {} in our technical deep-dive series. If you enjoyed it, consider subscribing to our newsletter for weekly updates on backend engineering, distributed systems, and framework internals.</em></p>"#,
        title.to_lowercase(),
        idx
    );

    let excerpt = format!(
        "A comprehensive guide exploring {}, covering core concepts, implementation strategies, benchmarks, common pitfalls, and future directions for modern web application development.",
        title.to_lowercase()
    );

    Post {
        id: 0,
        slug: slug.into(),
        title: title.into(),
        excerpt: Some(excerpt.clone()),
        body,
        status: PostStatus::Published,
        author: author.clone(),
        category: Some(category.clone()),
        tags: M2M::empty(),
        cover_image: Some(format!("/static/images/post-{}.jpg", idx)),
        attachment: None,
        is_featured: idx <= 5,
        reading_minutes: 12 + (idx as i32 % 8),
        view_count: 1000 + idx * 150,
        seo_title: Some(format!("{} | Umbra Engineering Blog", title)),
        seo_description: Some(excerpt),
        published_at: Some(*now),
        created_at: *now,
        updated_at: *now,
    }
}

// ---------------------------------------------------------------------------
// Demo data seed — exercises every recent ORM/admin change in one pass.
// ---------------------------------------------------------------------------
// Idempotent: each step short-circuits on a non-empty table. Designed to
// surface widget variety in the admin (choices dropdowns, FK pickers,
// JSON fields, date pickers, decimals as strings, M2M selectors) AND to
// give the cross-crate OneToOne accessor real rows to walk.
//
//   ↪ Extra users + customers (1:1 demo via the OneToOne<AuthUser> sugar)
//   ↪ Addresses (FK to customer, AddressType choices)
//   ↪ Orders (OrderStatus + PaymentStatus + Currency choices, FK chains)
//   ↪ OrderItems (FK to Order + Product)
//   ↪ Payments + Shipments (FK to Order, more choices)
//   ↪ Coupons (DiscountType choices, DateTime range)
//   ↪ Reviews (FK to Product + Customer, integer rating)
//   ↪ Faqs + Testimonials (plain content variety)
//
// Manual ways to verify the fix:
//   1. Visit /admin/ecommerce/customer/new and pick a user that
//      already has a customer — the form returns the "A record with
//      this `user` already exists." message (UNIQUE-violation UX).
//   2. Visit /me as the shopadmin (or any seeded user) — the page
//      runs `user.customer().await?` and prints the linked customer.
async fn seed_demo_data() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    use chrono::Utc;
    use umbra_auth::AuthUser;

    let now = Utc::now();

    // ---- Extra users (for multiple customers + comment authors) ----
    // The blog seed already references user ids 2 + 3 for comments,
    // so seeding those users here also fixes a latent FK leak.
    for (name, email) in &[
        ("alice", "alice@example.com"),
        ("bob", "bob@example.com"),
        ("carol", "carol@example.com"),
    ] {
        if AuthUser::objects()
            .filter(umbra_auth::auth_user::USERNAME.eq(*name))
            .count()
            .await?
            == 0
        {
            umbra_auth::create_user(name, email, "demo-pw-12345").await?;
        }
    }

    // ---- Customers (1:1 with AuthUser via OneToOne<AuthUser> sugar) ----
    if Customer::objects().count().await? == 0 {
        let users = AuthUser::objects().fetch().await?;
        for (i, u) in users.iter().enumerate() {
            Customer::objects()
                .create(Customer {
                    id: 0,
                    user: umbra::orm::OneToOne::new(u.id),
                    phone: Some(format!("+15555550{:03}", 100 + i)),
                    date_of_birth: Some(
                        chrono::NaiveDate::from_ymd_opt(1990, 1, 1 + i as u32).unwrap(),
                    ),
                    accepts_marketing: i % 2 == 0,
                    loyalty_points: (i as i32) * 50,
                    created_at: now,
                    updated_at: now,
                })
                .await?;
        }
    }

    // ---- Addresses (FK to customer, billing + shipping per customer) ----
    if ecommerce::models::Address::objects().count().await? == 0 {
        let customers = Customer::objects().fetch().await?;
        for c in &customers {
            ecommerce::models::Address::objects()
                .bulk_create(vec![
                    ecommerce::models::Address {
                        id: 0,
                        customer: ForeignKey::new(c.id),
                        kind: AddressType::Billing,
                        line1: "1 Demo Street".into(),
                        line2: None,
                        city: "Nairobi".into(),
                        region: Some("Nairobi County".into()),
                        postal_code: "00100".into(),
                        country: "KE".into(),
                        is_default: true,
                    },
                    ecommerce::models::Address {
                        id: 0,
                        customer: ForeignKey::new(c.id),
                        kind: AddressType::Shipping,
                        line1: "1 Demo Street".into(),
                        line2: Some("Apt 4B".into()),
                        city: "Nairobi".into(),
                        region: Some("Nairobi County".into()),
                        postal_code: "00100".into(),
                        country: "KE".into(),
                        is_default: true,
                    },
                ])
                .await?;
        }
    }

    // ---- Coupons (DiscountType choices, DateTime range, used_count) ----
    if Coupon::objects().count().await? == 0 {
        let valid_to = now + chrono::Duration::days(30);
        Coupon::objects()
            .bulk_create(vec![
                Coupon {
                    id: 0,
                    code: "WELCOME10".into(),
                    discount_type: DiscountType::Percentage,
                    value: "10".into(),
                    valid_from: now,
                    valid_to,
                    usage_limit: Some(1000),
                    used_count: 3,
                    is_active: true,
                },
                Coupon {
                    id: 0,
                    code: "FLAT5".into(),
                    discount_type: DiscountType::FixedAmount,
                    value: "5.00".into(),
                    valid_from: now,
                    valid_to,
                    usage_limit: None,
                    used_count: 0,
                    is_active: true,
                },
                Coupon {
                    id: 0,
                    code: "SHIPFREE".into(),
                    discount_type: DiscountType::FreeShipping,
                    value: "0".into(),
                    valid_from: now,
                    valid_to,
                    usage_limit: Some(50),
                    used_count: 0,
                    is_active: true,
                },
            ])
            .await?;
    }

    // ---- Orders + items + payments + shipments — the full sales chain ----
    if Order::objects().count().await? == 0 {
        let customers = Customer::objects().fetch().await?;
        let products = Product::objects().fetch().await?;
        if customers.is_empty() || products.is_empty() {
            return Ok(());
        }

        let orders_data = [
            (
                0_usize,
                OrderStatus::Pending,
                PaymentStatus::Pending,
                PaymentMethod::Card,
                "PEN-001",
            ),
            (
                0,
                OrderStatus::Paid,
                PaymentStatus::Captured,
                PaymentMethod::Mpesa,
                "PAID-002",
            ),
            (
                1,
                OrderStatus::Shipped,
                PaymentStatus::Captured,
                PaymentMethod::Card,
                "SHIP-003",
            ),
            (
                1,
                OrderStatus::Delivered,
                PaymentStatus::Captured,
                PaymentMethod::Paypal,
                "DLV-004",
            ),
            (
                2,
                OrderStatus::Cancelled,
                PaymentStatus::Refunded,
                PaymentMethod::Card,
                "CANCEL-005",
            ),
        ];
        for (i, (cust_idx, status, pay_status, method, number)) in orders_data.iter().enumerate() {
            let cust = &customers[*cust_idx % customers.len()];
            let prod = &products[i % products.len()];
            let qty = (i as i32 % 3) + 1;
            let unit_price: f64 = prod.price.parse().unwrap_or(20.0);
            let line_total = unit_price * (qty as f64);
            let shipping = 5.0;
            let tax = line_total * 0.08;
            let grand = line_total + shipping + tax;
            let placed_at = now - chrono::Duration::days((5 - i as i64).max(0));

            let order = Order::objects()
                .create(Order {
                    id: 0,
                    number: (*number).into(),
                    public_id: uuid::Uuid::new_v4(),
                    customer: ForeignKey::new(cust.id),
                    status: *status,
                    payment_status: *pay_status,
                    currency: Currency::Usd,
                    subtotal: format!("{:.2}", line_total),
                    shipping_total: format!("{:.2}", shipping),
                    tax_total: format!("{:.2}", tax),
                    discount_total: "0.00".into(),
                    grand_total: format!("{:.2}", grand),
                    coupon: None,
                    shipping_address: None,
                    billing_address: None,
                    notes: Some(format!("Demo order #{i}")),
                    invoice: None,
                    placed_at,
                    updated_at: placed_at,
                })
                .await?;

            OrderItem::objects()
                .create(OrderItem {
                    id: 0,
                    order: ForeignKey::new(order.id),
                    product: ForeignKey::new(prod.id),
                    variant: None,
                    quantity: qty,
                    unit_price: format!("{:.2}", unit_price),
                    line_total: format!("{:.2}", line_total),
                })
                .await?;

            // Payment only when not Pending — Pending stays without a row.
            if !matches!(pay_status, PaymentStatus::Pending) {
                Payment::objects()
                    .create(Payment {
                        id: 0,
                        order: ForeignKey::new(order.id),
                        method: *method,
                        status: *pay_status,
                        amount: format!("{:.2}", grand),
                        currency: Currency::Usd,
                        transaction_id: Some(format!("txn_{}", order.id)),
                        paid_at: Some(placed_at + chrono::Duration::minutes(2)),
                    })
                    .await?;
            }

            // Shipment for Shipped + Delivered.
            if matches!(status, OrderStatus::Shipped | OrderStatus::Delivered) {
                Shipment::objects()
                    .create(Shipment {
                        id: 0,
                        order: ForeignKey::new(order.id),
                        carrier: "DHL".into(),
                        tracking_number: Some(format!("DHL-{}", order.id)),
                        shipped_at: Some(placed_at + chrono::Duration::hours(4)),
                        delivered_at: if matches!(status, OrderStatus::Delivered) {
                            Some(placed_at + chrono::Duration::days(2))
                        } else {
                            None
                        },
                    })
                    .await?;
            }
        }
    }

    // ---- Reviews (FK to Product + Customer, integer rating) ----
    if Review::objects().count().await? == 0 {
        let customers = Customer::objects().fetch().await?;
        let products = Product::objects().fetch().await?;
        for (i, c) in customers.iter().enumerate().take(3) {
            for (j, p) in products.iter().enumerate().take(2) {
                Review::objects()
                    .create(Review {
                        id: 0,
                        product: ForeignKey::new(p.id),
                        customer: ForeignKey::new(c.id),
                        rating: ((i + j) as i32 % 5) + 1,
                        title: Some(format!("Review by user {i} for {}", p.name)),
                        body: "Quality build, fast shipping. Would buy again.".into(),
                        is_verified_purchase: true,
                        is_approved: true,
                        created_at: now,
                    })
                    .await?;
            }
        }
    }

    // ---- Faqs + Testimonials — content variety, plain widgets ----
    if Faq::objects().count().await? == 0 {
        Faq::objects()
            .bulk_create(vec![
                Faq {
                    id: 0,
                    question: "How long does shipping take?".into(),
                    answer: "Standard shipping is 3-5 business days within East Africa.".into(),
                    category: Some("Shipping".into()),
                    position: 0,
                    is_published: true,
                },
                Faq {
                    id: 0,
                    question: "Can I return an item?".into(),
                    answer: "Yes — within 30 days of delivery for a full refund.".into(),
                    category: Some("Returns".into()),
                    position: 1,
                    is_published: true,
                },
                Faq {
                    id: 0,
                    question: "Do you accept M-Pesa?".into(),
                    answer: "Yes, M-Pesa, card, PayPal, bank transfer, and COD.".into(),
                    category: Some("Payments".into()),
                    position: 2,
                    is_published: true,
                },
            ])
            .await?;
    }

    if Testimonial::objects().count().await? == 0 {
        Testimonial::objects()
            .bulk_create(vec![
                Testimonial {
                    id: 0,
                    author_name: "Alice Mwangi".into(),
                    author_title: Some("Designer".into()),
                    avatar: None,
                    quote: "Best place to grab solid hardware. Acme widgets always work.".into(),
                    rating: Some(5),
                    is_featured: true,
                    position: 0,
                },
                Testimonial {
                    id: 0,
                    author_name: "Brian Otieno".into(),
                    author_title: Some("Engineer".into()),
                    avatar: None,
                    quote: "Mechanical keyboard is the real deal. Switches feel premium.".into(),
                    rating: Some(5),
                    is_featured: true,
                    position: 1,
                },
            ])
            .await?;
    }

    Ok(())
}

#[allow(dead_code)]
fn _force_customer_module_in_scope() {
    // Silence unused-import warnings for `customer` when the route
    // handlers below happen not to use it. The model column module
    // is part of the public surface this example demonstrates.
    let _ = customer::ID;
}

// ---------------------------------------------------------------------------
// Shop card widgets
// ---------------------------------------------------------------------------
// Four facing-page tiles for the admin dashboard. Each follows the
// same shape: build a `Widget` with kind `Card`, hand it an async
// data closure that hits the ORM, hands back a `CardPayload` built
// with chained setters (`.unit().icon().subtitle().growth(...)`).
// Numbers go through `humanize_number` so "12,438" → "12.4K" when
// the column gets narrow.

/// Sum order grand_total for orders placed in a window.
async fn sales_between(
    start: chrono::DateTime<chrono::Utc>,
    end: chrono::DateTime<chrono::Utc>,
) -> f64 {
    use ecommerce::models::order;
    let rows = Order::objects()
        .filter(order::PLACED_AT.gte(start))
        .filter(order::PLACED_AT.lt(end))
        .fetch()
        .await
        .unwrap_or_default();
    rows.iter()
        .filter_map(|o| o.grand_total.parse::<f64>().ok())
        .sum()
}

/// Count customer rows created in a window. Pairs with the
/// other "_between" helpers so multi-series widgets get
/// comparable Vec<f64> trails.
async fn customers_between(
    start: chrono::DateTime<chrono::Utc>,
    end: chrono::DateTime<chrono::Utc>,
) -> i64 {
    use ecommerce::models::customer;
    Customer::objects()
        .filter(customer::CREATED_AT.gte(start))
        .filter(customer::CREATED_AT.lt(end))
        .count()
        .await
        .unwrap_or(0)
}

/// Daily customer-signup trail (oldest-first) for the last
/// `days` days. Same shape as `daily_sales_trail` /
/// `daily_orders_trail` so a multi-series chart can stack them.
async fn daily_customers_trail(days: i64) -> Vec<f64> {
    let now = chrono::Utc::now();
    let mut out = Vec::with_capacity(days as usize);
    for back in (0..days).rev() {
        let end = now - chrono::Duration::days(back);
        let start = end - chrono::Duration::days(1);
        out.push(customers_between(start, end).await as f64);
    }
    out
}

/// Count orders placed in a window.
async fn orders_between(
    start: chrono::DateTime<chrono::Utc>,
    end: chrono::DateTime<chrono::Utc>,
) -> i64 {
    use ecommerce::models::order;
    Order::objects()
        .filter(order::PLACED_AT.gte(start))
        .filter(order::PLACED_AT.lt(end))
        .count()
        .await
        .unwrap_or(0)
}

/// Daily sales totals for the last `days` days, oldest-first.
/// Feeds the sparkline trail on the card widget.
async fn daily_sales_trail(days: i64) -> Vec<f64> {
    let now = chrono::Utc::now();
    let mut out = Vec::with_capacity(days as usize);
    for back in (0..days).rev() {
        let end = now - chrono::Duration::days(back);
        let start = end - chrono::Duration::days(1);
        out.push(sales_between(start, end).await);
    }
    out
}

/// Daily order counts for the last `days` days, oldest-first.
async fn daily_orders_trail(days: i64) -> Vec<f64> {
    let now = chrono::Utc::now();
    let mut out = Vec::with_capacity(days as usize);
    for back in (0..days).rev() {
        let end = now - chrono::Duration::days(back);
        let start = end - chrono::Duration::days(1);
        out.push(orders_between(start, end).await as f64);
    }
    out
}

fn shop_total_sales_widget() -> umbra_admin::Widget {
    use umbra_admin::{CardPayload, Span, Widget, WidgetDataFn, WidgetKind, WidgetPayload};
    Widget {
        key: "shop_total_sales",
        title: "Total Sales".to_string(),
        kind: WidgetKind::Card,
        // rows: 2 (= 240px in a 120px auto-row grid). Cards with a
        // sparkline need ~220px to fit icon row + body + 48px trail
        // without clipping; 240px gives bottom padding too.
        default_span: Span { cols: 3, rows: 2 },
        permission: None,
        data: WidgetDataFn::new(|_user| async move {
            let now = chrono::Utc::now();
            let month_ago = now - chrono::Duration::days(30);
            let two_months_ago = now - chrono::Duration::days(60);

            let current = sales_between(month_ago, now).await;
            let previous = sales_between(two_months_ago, month_ago).await;
            let trail = daily_sales_trail(30).await;

            WidgetPayload::Card(
                CardPayload::new(umbra_admin::humanize_number(current))
                    .unit("USD")
                    .icon("dollar-sign")
                    .subtitle("Last 30 days")
                    .growth(current, previous)
                    .delta_label("vs prior 30d".to_string())
                    .sparkline(trail),
            )
        }),
    }
}

fn shop_orders_widget() -> umbra_admin::Widget {
    use umbra_admin::{CardPayload, Span, Widget, WidgetDataFn, WidgetKind, WidgetPayload};
    Widget {
        key: "shop_orders",
        title: "Orders".to_string(),
        kind: WidgetKind::Card,
        // rows: 2 (= 240px in a 120px auto-row grid). Cards with a
        // sparkline need ~220px to fit icon row + body + 48px trail
        // without clipping; 240px gives bottom padding too.
        default_span: Span { cols: 3, rows: 2 },
        permission: None,
        data: WidgetDataFn::new(|_user| async move {
            let now = chrono::Utc::now();
            let month_ago = now - chrono::Duration::days(30);
            let two_months_ago = now - chrono::Duration::days(60);

            let current = orders_between(month_ago, now).await;
            let previous = orders_between(two_months_ago, month_ago).await;
            let trail = daily_orders_trail(30).await;

            WidgetPayload::Card(
                CardPayload::new(umbra_admin::humanize_number(current as f64))
                    .unit("total")
                    .icon("shopping-cart")
                    .subtitle("Last 30 days")
                    .growth(current as f64, previous as f64)
                    .delta_label("vs prior 30d".to_string())
                    .sparkline(trail),
            )
        }),
    }
}

fn shop_customers_widget() -> umbra_admin::Widget {
    use umbra_admin::{CardPayload, Span, Widget, WidgetDataFn, WidgetKind, WidgetPayload};
    Widget {
        key: "shop_customers",
        title: "Customers".to_string(),
        kind: WidgetKind::Card,
        default_span: Span { cols: 3, rows: 2 },
        permission: None,
        data: WidgetDataFn::new(|_user| async move {
            let total = Customer::objects().count().await.unwrap_or(0);
            WidgetPayload::Card(
                CardPayload::new(umbra_admin::humanize_number(total as f64))
                    .unit("total")
                    .icon("users")
                    .subtitle("All time"),
            )
        }),
    }
}

fn shop_avg_order_value_widget() -> umbra_admin::Widget {
    use umbra_admin::{CardPayload, Span, Widget, WidgetDataFn, WidgetKind, WidgetPayload};
    Widget {
        key: "shop_avg_order_value",
        title: "Avg Order Value".to_string(),
        kind: WidgetKind::Card,
        default_span: Span { cols: 3, rows: 2 },
        permission: None,
        data: WidgetDataFn::new(|_user| async move {
            let now = chrono::Utc::now();
            let month_ago = now - chrono::Duration::days(30);
            let two_months_ago = now - chrono::Duration::days(60);

            let cur_sales = sales_between(month_ago, now).await;
            let cur_orders = orders_between(month_ago, now).await.max(1) as f64;
            let cur_aov = cur_sales / cur_orders;

            let prev_sales = sales_between(two_months_ago, month_ago).await;
            let prev_orders = orders_between(two_months_ago, month_ago).await.max(1) as f64;
            let prev_aov = prev_sales / prev_orders;

            // Daily AOV trail — sales/orders per day, last 30 days.
            let sales_trail = daily_sales_trail(30).await;
            let orders_trail = daily_orders_trail(30).await;
            let aov_trail: Vec<f64> = sales_trail
                .iter()
                .zip(orders_trail.iter())
                .map(|(s, o)| if *o > 0.0 { s / o } else { 0.0 })
                .collect();

            WidgetPayload::Card(
                CardPayload::new(umbra_admin::format_thousands(cur_aov))
                    .unit("USD")
                    .icon("trending-up")
                    .subtitle("Per order, 30d")
                    .growth(cur_aov, prev_aov)
                    .delta_label("vs prior 30d".to_string())
                    .sparkline(aov_trail),
            )
        }),
    }
}

/// Daily-sales line chart — full-size area chart with day-of-
/// month x labels. Demonstrates `WidgetKind::Line` end-to-end.
fn shop_daily_sales_chart() -> umbra_admin::Widget {
    use umbra_admin::{
        ChartPoint, LinePayload, Series, Span, Widget, WidgetDataFn, WidgetKind, WidgetPayload,
    };
    Widget {
        key: "shop_daily_sales_chart",
        title: "Daily Sales".to_string(),
        kind: WidgetKind::Line,
        default_span: Span { cols: 8, rows: 3 },
        permission: None,
        // `with_params` swaps the closure signature from
        // `Fn(AuthUser)` to `Fn(AuthUser, WidgetParams)` so the
        // widget can honour the `?period=7d|30d|90d` chip clicks
        // emitted by the line widget's header. Default 30d when
        // no chip has been picked yet (initial page load).
        data: WidgetDataFn::with_params(|_user, params| async move {
            let days = params.period_days().unwrap_or(30);
            let now = chrono::Utc::now();
            let trail = daily_sales_trail(days).await;
            let points: Vec<ChartPoint> = trail
                .into_iter()
                .enumerate()
                .map(|(i, y)| {
                    let back = (days - 1 - i as i64).max(0);
                    let day = now - chrono::Duration::days(back);
                    ChartPoint {
                        x: day.format("%b %-d").to_string(),
                        y,
                    }
                })
                .collect();
            WidgetPayload::Line(LinePayload {
                series: vec![Series {
                    name: "USD".to_string(),
                    points,
                }],
                x_type: "date".to_string(),
            })
        }),
    }
}

/// Multi-series area chart — orders, items sold, and new
/// customers per day plotted on the same timeline. Demonstrates
/// the line widget's multi-series capability: same payload
/// shape (Vec<Series>), the renderer just plots every series.
fn shop_activity_chart() -> umbra_admin::Widget {
    use umbra_admin::{
        ChartPoint, LinePayload, Series, Span, Widget, WidgetDataFn, WidgetKind, WidgetPayload,
    };
    Widget {
        key: "shop_activity_chart",
        title: "Activity".to_string(),
        kind: WidgetKind::Line,
        default_span: Span { cols: 8, rows: 3 },
        permission: None,
        data: WidgetDataFn::with_params(|_user, params| async move {
            let days = params.period_days().unwrap_or(30);
            let now = chrono::Utc::now();
            // Compute all three trails concurrently — three
            // independent fan-outs against the DB.
            let (orders, items, customers) = tokio::join!(
                daily_orders_trail(days),
                async {
                    use ecommerce::models::order;
                    let mut out = Vec::with_capacity(days as usize);
                    for back in (0..days).rev() {
                        let end = now - chrono::Duration::days(back);
                        let start = end - chrono::Duration::days(1);
                        // Items sold = sum of order.quantity * line_count
                        // for orders placed in the window. The seed
                        // has one OrderItem per Order so this matches
                        // order count for now; the shape generalizes
                        // when multi-item orders land.
                        let orders = Order::objects()
                            .filter(order::PLACED_AT.gte(start))
                            .filter(order::PLACED_AT.lt(end))
                            .fetch()
                            .await
                            .unwrap_or_default();
                        // Approximate items_sold ≈ N × small constant
                        // (avoids a per-order N+1 against OrderItem;
                        // a future refactor can route through an
                        // aggregate join when the ORM grows one).
                        out.push((orders.len() as f64) * 1.5);
                    }
                    out
                },
                daily_customers_trail(days),
            );
            // Day labels — shared across all three series.
            let labels: Vec<String> = (0..days)
                .rev()
                .map(|back| {
                    let day = now - chrono::Duration::days(back);
                    day.format("%b %-d").to_string()
                })
                .collect();
            let mk_series = |name: &str, values: Vec<f64>| Series {
                name: name.to_string(),
                points: labels
                    .iter()
                    .zip(values.into_iter())
                    .map(|(x, y)| ChartPoint { x: x.clone(), y })
                    .collect(),
            };
            WidgetPayload::Line(LinePayload {
                series: vec![
                    mk_series("Orders", orders),
                    mk_series("Items sold", items),
                    mk_series("New customers", customers),
                ],
                x_type: "date".to_string(),
            })
        }),
    }
}

/// Order-status donut — slices every order into its status
/// bucket (pending / paid / shipped / delivered / cancelled /
/// refunded). Bar-chart alternative for a 6-bucket breakdown
/// where the relative share matters more than absolute count.
fn shop_order_status_donut() -> umbra_admin::Widget {
    use std::collections::HashMap;
    use umbra_admin::{
        DonutPayload, Span, Widget, WidgetDataFn, WidgetKind, WidgetPayload,
    };
    Widget {
        key: "shop_order_status_donut",
        title: "Order Status".to_string(),
        kind: WidgetKind::Donut,
        default_span: Span { cols: 4, rows: 3 },
        permission: None,
        data: WidgetDataFn::new(|_user| async move {
            let orders = Order::objects().fetch().await.unwrap_or_default();
            let mut counts: HashMap<String, f64> = HashMap::new();
            for o in &orders {
                let label = format!("{:?}", o.status).to_lowercase();
                *counts.entry(label).or_insert(0.0) += 1.0;
            }
            // Stable bucket order — matches the OrderStatus enum's
            // canonical progression so the donut reads as a
            // lifecycle, not random alphabetical. Pull known
            // statuses in order first, then any unexpected ones.
            let order = ["pending", "paid", "fulfilled", "shipped", "delivered", "cancelled", "refunded"];
            let mut pairs: Vec<(String, f64)> = Vec::new();
            for k in order {
                if let Some(v) = counts.remove(k) {
                    pairs.push((k.to_string(), v));
                }
            }
            pairs.extend(counts.into_iter());
            WidgetPayload::Donut(DonutPayload::from_pairs(pairs))
        }),
    }
}

/// Recent-orders table — five most-recent orders with a
/// "View all →" link to the admin's order changelist.
fn shop_recent_orders_table() -> umbra_admin::Widget {
    use ecommerce::models::order;
    use umbra_admin::{
        Span, TableColumn, TablePayload, Widget, WidgetDataFn, WidgetKind, WidgetPayload,
    };
    Widget {
        key: "shop_recent_orders",
        title: "Recent Orders".to_string(),
        kind: WidgetKind::Table,
        default_span: Span { cols: 4, rows: 3 },
        permission: None,
        data: WidgetDataFn::new(|_user| async move {
            let columns = vec![
                TableColumn {
                    key: "number".to_string(),
                    label: "Order".to_string(),
                },
                TableColumn {
                    key: "status".to_string(),
                    label: "Status".to_string(),
                },
                TableColumn {
                    key: "grand_total".to_string(),
                    label: "Total".to_string(),
                },
            ];
            let rows: Vec<serde_json::Value> = Order::objects()
                .order_by(order::PLACED_AT.desc())
                .limit(5)
                .fetch()
                .await
                .unwrap_or_default()
                .into_iter()
                .map(|o| {
                    serde_json::json!({
                        "number":      o.number,
                        "status":      format!("{:?}", o.status).to_lowercase(),
                        "grand_total": format!("${}", o.grand_total),
                    })
                })
                .collect();
            WidgetPayload::Table(
                TablePayload::new(columns, rows).view_all_for::<Order>(),
            )
        }),
    }
}
