//! shop — generated by `umbra startproject shop`.
//!
//! Full e-commerce + content example app. Wires auth, sessions, permissions,
//! admin, REST with filters, content plugin, and ecommerce plugin.
//!
//! Run with:
//!   cargo run -- migrate   # apply pending migrations
//!   cargo run -- serve     # boot the HTTP server
//!   cargo run -- makemigrations
//!   cargo run -- showmigrations
//!   cargo run -- createsuperuser
//!
//! Layout:
//!   src/
//!     main.rs    — App builder + HTTP handlers (this file, kept short)
//!     auth.rs    — Custom Token-scheme authenticator
//!     seed/      — Idempotent demo-data seed split by concern
//!                  (credentials / products / demo_data / blogs)
//!     widgets/   — Dashboard widgets grouped by kind
//!                  (cards / charts / tables / content)

mod auth;
mod seed;
mod views;
mod widgets;

use std::sync::Arc;

use content::ContentPlugin;
use ecommerce::EcommercePlugin;
use umbra::migrate::MigrateError;
use umbra::prelude::*;
use umbra::web::SlashRedirect;
use umbra_admin::{AdminModel, AdminPlugin};
use umbra_auth::{AuthPlugin, AuthUser, BearerAuthentication, login_required_html};
use umbra_openapi::OpenApiPlugin;
use umbra_permissions::{PermissionsPlugin, permission_required_html};
use umbra_playground::PlaygroundPlugin;
use umbra_rest::{
    Authentication, ChainAuthentication, IsAuthenticated, IsStaff, OrPermission,
    PageNumberPagination, ReadOnly, ResourceConfig, RestPlugin,
};
use umbra_sessions::SessionsPlugin;

use crate::auth::{TokenSchemeAuthentication, session_authentication};

// Handlers live in `src/views/`; the route table references
// them as `views::home`, `views::dashboard`, etc. The
// `mod views;` declaration above already brings the name into
// scope, so no `use` line is needed.

// ---------------------------------------------------------------------------
// App wiring
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let settings = Settings::from_env()?;
    let pool = umbra::db::connect(&settings.database_url).await?;

    let app = App::builder()
        .settings(settings)
        .database("default", pool)
        // --- Plugins ---------------------------------------------------------
        .plugin(AuthPlugin::<AuthUser>::default().with_default_routes())
        .plugin(SessionsPlugin::default())
        .plugin(PermissionsPlugin)
        .plugin(ContentPlugin)
        .plugin(EcommercePlugin)
        // Admin: declare per-model search + filter columns on the
        // ecommerce side so the changelist toolbar shows the search
        // input + Filter button. `register_for("ecommerce", ...)` keeps
        // the sidebar grouping AND the per-model permission codenames
        // (`ecommerce.view_product`, etc.) aligned with the plugin
        // that owns each model.
        .plugin(
            AdminPlugin::default()
                .site_title("Shop".to_string())
                .register_for(
                    "ecommerce",
                    AdminModel::new("product")
                        .search_fields(&["name", "sku", "slug"])
                        .list_filter(&["status", "category", "brand", "is_featured", "currency"]),
                )
                .register_for(
                    "ecommerce",
                    AdminModel::new("brand").search_fields(&["name", "slug"]),
                )
                .register_for(
                    "ecommerce",
                    AdminModel::new("order")
                        .search_fields(&["number"])
                        .list_filter(&["status", "payment_status", "currency"]),
                )
                .register(
                    umbra_admin::AdminModel::new("auth_user")
                        .label("Users")
                        .icon("users")
                        .password_field("password_hash"),
                )
                // Dashboard layout — named sections, curated model
                // grid. Widgets live in `src/widgets/`; see that
                // module's docstring for which file owns each builder.
                .dashboard_models_title("Data")
                .dashboard_models_subtitle("Jump straight to a managed table")
                .dashboard_models_only(&umbra::models![
                    ecommerce::models::Product,
                    ecommerce::models::Order,
                    ecommerce::models::Customer,
                    ecommerce::models::Brand,
                    ecommerce::models::Coupon,
                    content::models::Post,
                ])
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Sales overview")
                        .subtitle("Daily KPIs across the storefront")
                        .widget(widgets::shop_total_sales_widget())
                        .widget(widgets::shop_orders_widget())
                        .widget(widgets::shop_customers_widget())
                        .widget(widgets::shop_avg_order_value_widget()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Trends")
                        .subtitle(
                            "Daily sales + multi-series activity + status mix + recent orders",
                        )
                        .widget(widgets::shop_daily_sales_chart().with_default_period("7d"))
                        .widget(widgets::shop_recent_orders_table())
                        .widget(widgets::shop_activity_chart().with_default_period("7d"))
                        .widget(widgets::shop_order_status_donut()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Content")
                        .subtitle("Editorial activity from the content plugin")
                        .widget(widgets::content_subscribers_card())
                        .widget(widgets::content_post_status_donut())
                        .widget(widgets::content_recent_posts_table()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("System")
                        .subtitle("Framework-wide health + recent activity")
                        .widget(umbra_admin::builtin_total_models_widget().with_span(8, 2))
                        .widget(umbra_admin::builtin_recent_users_widget().with_span(4, 2)),
                ),
        )
        // REST: three resources, three different auth + permission
        // postures, plus per-resource field-exposure controls. The
        // global authenticator is a CHAIN — try session first, then
        // Bearer, then the custom `Token <T>` scheme.
        .plugin(
            RestPlugin::default()
                .paginate(PageNumberPagination::new(20))
                .authenticate(ChainAuthentication::new(vec![
                    Arc::new(session_authentication()) as Arc<dyn Authentication>,
                    Arc::new(BearerAuthentication::default()) as Arc<dyn Authentication>,
                    Arc::new(TokenSchemeAuthentication::default()) as Arc<dyn Authentication>,
                ]))
                .resource(ResourceConfig::new("product").hide("cost").permission(
                    OrPermission::new(vec![Box::new(ReadOnly), Box::new(IsStaff)]),
                ))
                .resource(ResourceConfig::new("order").permission(IsAuthenticated))
                .resource(
                    ResourceConfig::new("post").permission(OrPermission::new(vec![
                        Box::new(ReadOnly),
                        Box::new(IsStaff),
                    ])),
                ),
        )
        .plugin(OpenApiPlugin::new())
        .plugin(PlaygroundPlugin::new("shop"))
        // --- Templates -------------------------------------------------------
        .templates_dir("templates")
        .not_found_template("404.html")
        .server_error_template("500.html")
        .slash_redirect(SlashRedirect::Append)
        // --- Routes ----------------------------------------------------------
        .routes(
            Routes::new()
                .get("/", views::home)
                .get("/products", views::product_list)
                .get("/products/{id}", views::product_detail)
                .layered(
                    "GET",
                    "/dashboard",
                    get(views::dashboard).layer(login_required_html("/login")),
                )
                .layered(
                    "GET",
                    "/staff-only",
                    get(views::staff_only)
                        .layer(permission_required_html("ecommerce.view_product", "/login")),
                )
                .layered(
                    "GET",
                    "/me",
                    get(views::me).layer(login_required_html("/login")),
                ),
        )
        .build()?;

    if is_serve_invocation() {
        auto_migrate().await?;
        // One call now — `seed::all()` runs the per-concern files
        // (credentials → products → demo_data → blogs) in the right
        // order. Idempotent: re-running tops up missing rows
        // without re-inserting.
        seed::all().await?;
    }

    umbra_cli::dispatch(app).await
}

// ---------------------------------------------------------------------------
// Boot helpers
// ---------------------------------------------------------------------------

fn is_serve_invocation() -> bool {
    matches!(std::env::args().nth(1).as_deref(), None | Some("serve"))
}

async fn auto_migrate() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    match umbra::migrate::make().await {
        Ok(paths) => {
            for path in paths {
                eprintln!("auto-migrate: wrote {}", path.display());
            }
        }
        Err(MigrateError::NoChanges) => {}
        Err(err) => return Err(Box::new(err)),
    }
    let n = umbra::migrate::run().await?;
    if n > 0 {
        eprintln!("auto-migrate: applied {n} migration(s)");
    }
    Ok(())
}
