//! shop — generated by `umbra startproject shop`.
//!
//! Full e-commerce + content example app. Wires auth, sessions, permissions,
//! admin, REST with filters, content plugin, and ecommerce plugin.
//!
//! Run with:
//!   cargo run -- migrate   # apply pending migrations
//!   cargo run -- serve     # boot the HTTP server
//!   cargo run -- makemigrations
//!   cargo run -- showmigrations
//!   cargo run -- createsuperuser
//!
//! Layout:
//!   src/
//!     main.rs    — App builder + HTTP handlers (this file, kept short)
//!     auth.rs    — Custom Token-scheme authenticator
//!     seed/      — Idempotent demo-data seed split by concern
//!                  (credentials / products / demo_data / blogs)
//!     widgets/   — Dashboard widgets grouped by kind
//!                  (cards / charts / tables / content)

mod auth;
mod seed;
mod views;
mod widgets;

use std::sync::Arc;

use content::ContentPlugin;
use ecommerce::EcommercePlugin;
use umbra::cors::CorsConfig;
use umbra::migrate::MigrateError;
use umbra::prelude::*;
use umbra::web::SlashRedirect;
use umbra_admin::{AdminModel, AdminPlugin};
use umbra_auth::{AuthPlugin, AuthUser, BearerAuthentication, login_required_html};
use umbra_openapi::OpenApiPlugin;
use umbra_permissions::{PermissionsPlugin, permission_required_html};
use umbra_playground::PlaygroundPlugin;
use umbra_rest::{
    Authentication, ChainAuthentication, IsAuthenticated, IsStaff, OrPermission,
    PageNumberPagination, ReadOnly, ResourceConfig, RestPlugin,
};
use umbra_security::{SecurityConfig, SecurityPlugin};
use umbra_sessions::SessionsPlugin;
use umbra_storage::StoragePlugin;

use crate::auth::{TokenSchemeAuthentication, session_authentication};

// Handlers live in `src/views/`; the route table references
// them as `views::home`, `views::dashboard`, etc. The
// `mod views;` declaration above already brings the name into
// scope, so no `use` line is needed.

// ---------------------------------------------------------------------------
// App wiring
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    // Observability: structured logging + OpenTelemetry OTLP trace export
    // (the `otel` feature on umbra-logs is on for the shop). Env knobs:
    // RUST_LOG, UMBRA_LOG_FORMAT=json, OTEL_EXPORTER_OTLP_ENDPOINT (default
    // http://localhost:4317), OTEL_SERVICE_NAME. The guard flushes the OTLP
    // exporter on drop, so keep it alive for the whole program.
    let _obs = umbra_logs::observability::init(
        umbra_logs::ObservabilityConfig::from_env().service_name("umbra-shop"),
    );

    let settings = Settings::from_env()?;
    eprintln!(
        "loaded host config: allowed_hosts={:?} env={:?}\n  unmapped UMBRA_ keys (extra) = {:?}",
        settings.allowed_hosts,
        settings.environment,
        settings.extra.keys().collect::<Vec<_>>()
    );
    let pool = umbra::db::connect(&settings.database_url).await?;

    let app = App::builder()
        .settings(settings)
        .database("default", pool)
        // --- Plugins ---------------------------------------------------------
        .plugin(
            AuthPlugin::<AuthUser>::default()
                .with_default_routes()
                // Mounts `user_context_layer` globally — every
                // template render gets `user` in its context
                // (`is_authenticated`, `is_staff`, `username`, ...).
                // Cost: one DB read per request. Worth it for an
                // HTML-heavy app; would be off for REST-only.
                .with_user_in_templates(),
        )
        .plugin(SessionsPlugin::default())
        .plugin(PermissionsPlugin)
        .plugin(ContentPlugin)
        .plugin(EcommercePlugin)
        // Admin: declare per-model search + filter columns on the
        // ecommerce side so the changelist toolbar shows the search
        // input + Filter button. `register_for("ecommerce", ...)` keeps
        // the sidebar grouping AND the per-model permission codenames
        // (`ecommerce.view_product`, etc.) aligned with the plugin
        // that owns each model.
        .plugin(
            AdminPlugin::default()
                .site_title("Shop".to_string())
                .register_for(
                    "ecommerce",
                    AdminModel::new("product")
                        .search_fields(&["name", "sku", "slug"])
                        .list_filter(&["status", "category", "brand", "is_featured", "currency"]),
                )
                .register_for(
                    "ecommerce",
                    AdminModel::new("brand").search_fields(&["name", "slug"]),
                )
                .register_for(
                    "ecommerce",
                    AdminModel::new("order")
                        .search_fields(&["number"])
                        .list_filter(&["status", "payment_status", "currency"]),
                )
                .register(
                    umbra_admin::AdminModel::new("auth_user")
                        .label("Users")
                        .icon("users")
                        .password_field("password_hash"),
                )
                // Dashboard layout — named sections, curated model
                // grid. Widgets live in `src/widgets/`; see that
                // module's docstring for which file owns each builder.
                .dashboard_models_title("Data")
                .dashboard_models_subtitle("Jump straight to a managed table")
                .dashboard_models_only(&umbra::models![
                    ecommerce::models::Product,
                    ecommerce::models::Order,
                    ecommerce::models::Customer,
                    ecommerce::models::Brand,
                    ecommerce::models::Coupon,
                    content::models::Post,
                ])
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Sales overview")
                        .subtitle("Daily KPIs across the storefront")
                        .widget(widgets::shop_total_sales_widget())
                        .widget(widgets::shop_orders_widget())
                        .widget(widgets::shop_customers_widget())
                        .widget(widgets::shop_avg_order_value_widget()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Trends")
                        .subtitle(
                            "Daily sales + multi-series activity + status mix + recent orders",
                        )
                        .widget(widgets::shop_daily_sales_chart().with_default_period("7d"))
                        .widget(widgets::shop_recent_orders_table())
                        .widget(widgets::shop_activity_chart().with_default_period("7d"))
                        .widget(widgets::shop_order_status_donut()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Gauges & rankings")
                        .subtitle("Radial gauge, calendar heatmap, and a ranked bar list")
                        .widget(widgets::shop_fulfillment_radial())
                        .widget(widgets::shop_sales_heatmap())
                        .widget(widgets::shop_order_status_progress()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("Content")
                        .subtitle("Editorial activity from the content plugin")
                        .widget(widgets::content_subscribers_card())
                        .widget(widgets::content_post_status_donut())
                        .widget(widgets::content_recent_posts_table()),
                )
                .dashboard_section(
                    umbra_admin::WidgetSection::new("System")
                        .subtitle("Framework-wide health + recent activity")
                        .widget(umbra_admin::builtin_total_models_widget().with_span(8, 2))
                        .widget(umbra_admin::builtin_recent_users_widget().with_span(4, 2)),
                ),
        )
        // REST: three resources, three different auth + permission
        // postures, plus per-resource field-exposure controls. The
        // global authenticator is a CHAIN — try session first, then
        // Bearer, then the custom `Token <T>` scheme.
        .plugin(
            RestPlugin::default()
                .paginate(PageNumberPagination::new(20))
                .authenticate(ChainAuthentication::new(vec![
                    Arc::new(session_authentication()) as Arc<dyn Authentication>,
                    Arc::new(BearerAuthentication::default()) as Arc<dyn Authentication>,
                    Arc::new(TokenSchemeAuthentication::default()) as Arc<dyn Authentication>,
                ]))
                .resource(ResourceConfig::new("product").hide("cost").permission(
                    OrPermission::new(vec![Box::new(ReadOnly), Box::new(IsStaff)]),
                ))
                .resource(ResourceConfig::new("order").permission(IsAuthenticated))
                .resource(
                    ResourceConfig::new("post").permission(OrPermission::new(vec![
                        Box::new(ReadOnly),
                        Box::new(IsStaff),
                    ])),
                ),
        )
        .plugin(OpenApiPlugin::new().at("/api/docs"))
        .plugin(PlaygroundPlugin::new("shop"))
        // gaps2 #20: serve compiled Tailwind (styles/input.css →
        // static/css/shop.css via build.rs) instead of the CDN. The
        // wrapper.html template references /static/css/shop.css.
        // Self-hosted Inter woff2 files live alongside the CSS.
        .plugin(StoragePlugin::new().static_files("/static", "./static"))
        // CSRF + hardening headers across the whole app. `/api` is exempt
        // because the REST surface authenticates by bearer token (no session
        // cookie), so the double-submit check doesn't apply there. HSTS stays
        // off for local http dev (flip it on behind a prod profile).
        .plugin(SecurityPlugin::with_config(SecurityConfig {
            csrf_exempt_paths: vec!["/api".to_string()],
            ..Default::default()
        }))
        // CORS scoped to the REST API only (`/api`) — the HTML pages stay
        // same-origin. Strict by default (deny all cross-origin); opt in to the
        // origins a browser frontend on another host uses to call the API.
        // Batch form via `allow_origins(vec![...])`. Swap these for your real
        // frontend origins.
        .cors_for(
            "/api",
            CorsConfig::strict()
                .allow_origins(vec!["http://localhost:3000", "http://localhost:5173"])
                .allow_credentials(true),
        )
        // --- Templates -------------------------------------------------------
        .templates_dir("templates")
        .not_found_template("404.html")
        .server_error_template("500.html")
        .slash_redirect(SlashRedirect::Append)
        // --- Routes ----------------------------------------------------------
        .routes(
            Routes::new()
                .get("/", views::home)
                .get("/bench/json", views::bench_json)
                .get("/bench/text", views::bench_text)
                .get("/bench/notes/write", views::bench_note_write)
                .get("/bench/notes/read", views::bench_note_read)
                .get("/products", views::product_list)
                .get("/products/{id}", views::product_detail)
                .get("/posts", views::post_list)
                .get("/posts/{slug}", views::post_detail)
                .get("/faqs", views::faqs)
                .get("/contact", views::contact)
                .post("/contact", views::submit_contact)
                .layered(
                    "GET",
                    "/dashboard",
                    get(views::dashboard).layer(login_required_html("/login")),
                )
                .layered(
                    "GET",
                    "/staff-only",
                    get(views::staff_only)
                        .layer(permission_required_html("ecommerce.view_product", "/login")),
                )
                .layered(
                    "GET",
                    "/me",
                    get(views::me).layer(login_required_html("/login")),
                ),
        )
        .build()?;

    if is_serve_invocation() {
        auto_migrate().await?;
        // One call now — `seed::all()` runs the per-concern files
        // (credentials → products → demo_data → blogs) in the right
        // order. Idempotent: re-running tops up missing rows
        // without re-inserting.
        seed::all().await?;
    }

    umbra_cli::dispatch(app).await
}

// ---------------------------------------------------------------------------
// Boot helpers
// ---------------------------------------------------------------------------

fn is_serve_invocation() -> bool {
    matches!(std::env::args().nth(1).as_deref(), None | Some("serve"))
}

async fn auto_migrate() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    match umbra::migrate::make().await {
        Ok(paths) => {
            for path in paths {
                eprintln!("auto-migrate: wrote {}", path.display());
            }
        }
        Err(MigrateError::NoChanges) => {}
        Err(err) => return Err(Box::new(err)),
    }
    let n = umbra::migrate::run().await?;
    if n > 0 {
        eprintln!("auto-migrate: applied {n} migration(s)");
    }
    Ok(())
}
