//! Standalone umbra example: `#[derive(Model)]` on a user-defined struct,
//! served over HTTP.
//!
//! Every umbra symbol in this file comes through the `umbra` facade. There
//! is no `umbra_core::` or `umbra_macros::` anywhere. The derive itself is
//! re-exported as `umbra::orm::Model` (the macro), sharing its name with
//! the `Model` trait via Rust's separate type and macro namespaces — both
//! ride in on `use umbra::prelude::*;` together.
//!
//! Compare with `examples/hello/`: that example uses the built-in `Post`
//! fixture model from `umbra::orm`. This one defines its own `Article`
//! struct and gets the same `objects()` entry point, the same `TABLE`
//! constant, and the same sibling column module from the derive — with
//! zero hand-written `impl Model` boilerplate.

use umbra::prelude::*;
use umbra::web::StatusCode;

/// A small article model.
///
/// The derive emits:
///
/// - `impl umbra::orm::Model for Article` with `TABLE = "article"` (the
///   snake_case of the struct name) and `FIELDS` populated from the
///   struct's fields in declaration order.
/// - `Article::objects() -> Manager<Article>` so handlers can reach the
///   QuerySet without threading a pool through.
/// - A sibling `mod article` of typed column constants in
///   SCREAMING_SNAKE_CASE: `article::ID`, `article::TITLE`,
///   `article::BODY`, `article::PUBLISHED_AT`.
///
/// `serde::Serialize` lets the handler return `Json<Vec<Article>>`.
/// `sqlx::FromRow` is what the QuerySet terminals use to materialise rows;
/// it's required by the `Model` trait's supertrait bound, so the derive
/// expects it on the struct.
// `pub` on the struct rather than the default private visibility: the derive
// emits `pub const` column constants in the sibling `mod article`, and
// rustc's `private_interfaces` lint flags those constants for referencing a
// less-visible type. In a real downstream crate the user-defined model is
// almost always `pub` anyway; this matches that shape.
#[derive(Debug, Clone, serde::Serialize, sqlx::FromRow, Model)]
pub struct Article {
    pub id: i64,
    pub title: String,
    pub body: String,
    pub published_at: Option<chrono::DateTime<chrono::Utc>>,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // `App::serve` emits its bind line via `tracing::info!`. Without a
    // subscriber that line is dropped. `EnvFilter` honours `RUST_LOG` so
    // the default verbosity can be tuned without rebuilding.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let settings = Settings::from_env()?;

    // Override `sqlite::memory:` with a file-backed URL for the same reason
    // umbra-cli does: a multi-connection sqlx pool with bare `:memory:`
    // gives each connection its own isolated database, so seeded rows on
    // one connection are invisible to handlers running on another. A file
    // is the simplest fix. Anything serious overrides UMBRA_DATABASE_URL.
    let database_url = if settings.database_url == "sqlite::memory:" {
        "sqlite://derive-demo.db?mode=rwc".to_string()
    } else {
        settings.database_url.clone()
    };
    let pool = umbra::db::connect(&database_url).await?;

    // Demo seed. CREATE TABLE IF NOT EXISTS + INSERT OR IGNORE so re-runs
    // are idempotent. M5's `migrate` retires this and `Manager::create`
    // (a later milestone) retires the seed INSERTs.
    init_article_table(&pool).await?;
    seed_article_rows(&pool).await?;

    let app = App::builder()
        .settings(settings)
        .database("default", pool)
        .router(
            Router::new()
                .route("/", get(|| async { "umbra-derive-demo" }))
                .route("/articles", get(list_articles)),
        )
        .build()?;

    // 3001 keeps the port distinct from `examples/hello/` (3000) and
    // umbra-cli (8000) so all three can run side-by-side on the same host.
    app.serve("127.0.0.1:3001".parse::<std::net::SocketAddr>()?)
        .await?;

    Ok(())
}

/// The Django-shape handler. Notice what isn't here: no pool parameter,
/// no `.on(&pool)` on the QuerySet, no `State<DbPool>` extractor. The
/// `Article::objects()` Manager picks up the ambient pool the
/// `App::build()` installed in `umbra::db`'s `OnceLock`, and the terminal
/// `.fetch().await` runs against it.
///
/// `Article::objects()` is generated by the derive. `article::ID` lives in
/// the sibling column module the derive also generates.
async fn list_articles() -> Result<Json<Vec<Article>>, (StatusCode, String)> {
    let articles = Article::objects()
        .order_by(article::ID.asc())
        .fetch()
        .await
        .map_err(|err| (StatusCode::INTERNAL_SERVER_ERROR, err.to_string()))?;
    Ok(Json(articles))
}

/// Raw sqlx CREATE TABLE for the demo seed. Goes away at M5 when `migrate`
/// generates and applies this from the model definition.
async fn init_article_table(pool: &sqlx::SqlitePool) -> Result<(), sqlx::Error> {
    sqlx::query(
        "CREATE TABLE IF NOT EXISTS article (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            body TEXT NOT NULL,
            published_at TEXT
        )",
    )
    .execute(pool)
    .await?;
    Ok(())
}

/// Two seed rows so `GET /articles` returns something on a fresh DB.
/// `INSERT OR IGNORE` keeps re-runs idempotent. Retired by
/// `Manager::create` once that lands.
async fn seed_article_rows(pool: &sqlx::SqlitePool) -> Result<(), sqlx::Error> {
    sqlx::query(
        "INSERT OR IGNORE INTO article (id, title, body, published_at) VALUES \
         (1, 'Deriving Model', 'this row came back through Article::objects().fetch()', '2026-05-30T12:00:00Z'), \
         (2, 'User-defined struct', 'no hand-written impl Model anywhere in this file', NULL)",
    )
    .execute(pool)
    .await?;
    Ok(())
}
