// Code generated by `umbral gen-client`. DO NOT EDIT.
//
// Regenerate after any model or REST-resource change:
//     cargo run -- gen-client --out <this directory>
//
// A typed client for this app's REST API. Base path: /api
// Pagination: None. Row types live in ./models.ts.

import type { CgAuthor, CgPost, CgPostStatus, CgTicket } from "./models";
export * from "./models";

/** Filterable query parameters for `cg_author`. Every key is optional and AND-combined server-side. */
export interface CgAuthorFilters {
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
}
export type CgAuthorOrdering = "slug" | "-slug" | "name" | "-name";
/** Body for creating a `cg_author`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface CgAuthorCreate {
  name: string;
}
/** Body for updating a `cg_author` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface CgAuthorUpdate {
  name?: string;
}

/** Filterable query parameters for `cg_post`. Every key is optional and AND-combined server-side. */
export interface CgPostFilters {
  "title"?: string;
  "title__ne"?: string;
  "title__contains"?: string;
  "title__icontains"?: string;
  "title__startswith"?: string;
  "title__in"?: string[];
  "body"?: string;
  "body__ne"?: string;
  "body__contains"?: string;
  "body__icontains"?: string;
  "body__startswith"?: string;
  "body__in"?: string[];
  "body__isnull"?: boolean;
  "status"?: CgPostStatus;
  "status__ne"?: CgPostStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: CgPostStatus[];
  "views"?: number;
  "views__ne"?: number;
  "views__gte"?: number;
  "views__lte"?: number;
  "views__gt"?: number;
  "views__lt"?: number;
  "views__in"?: number[];
  "author"?: string;
  "author__ne"?: string;
  "author__in"?: string[];
  "slug"?: string;
  "slug__ne"?: string;
  "slug__contains"?: string;
  "slug__icontains"?: string;
  "slug__startswith"?: string;
  "slug__in"?: string[];
  "internal"?: string;
  "internal__ne"?: string;
  "internal__contains"?: string;
  "internal__icontains"?: string;
  "internal__startswith"?: string;
  "internal__in"?: string[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
}
export type CgPostOrdering = "id" | "-id" | "title" | "-title" | "body" | "-body" | "status" | "-status" | "views" | "-views" | "author" | "-author" | "slug" | "-slug" | "internal" | "-internal" | "created_at" | "-created_at";
/** Body for creating a `cg_post`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface CgPostCreate {
  title: string;
  body?: string | null;
  status: CgPostStatus;
  views: number;
  author: string;
  slug: string;
}
/** Body for updating a `cg_post` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface CgPostUpdate {
  title?: string;
  body?: string | null;
  status?: CgPostStatus;
  views?: number;
  author?: string;
}

/** Filterable query parameters for `cg_ticket`. Every key is optional and AND-combined server-side. */
export interface CgTicketFilters {
  "subject"?: string;
  "subject__ne"?: string;
  "subject__contains"?: string;
  "subject__icontains"?: string;
  "subject__startswith"?: string;
  "subject__in"?: string[];
}
export type CgTicketOrdering = "id" | "-id" | "subject" | "-subject";
/** Body for creating a `cg_ticket`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface CgTicketCreate {
  subject: string;
}
/** Body for updating a `cg_ticket` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface CgTicketUpdate {
  subject?: string;
}

/** A list response. `results` + `count` are always present; the rest depend on the paginator. */
export interface Paginated<T> {
  results: T[];
  count: number;
}

/** Maps each REST-exposed table to its row, filter, and ordering types. `Umbral.from` keys off this. */
export interface UmbralResources {
  "cg_author": { row: CgAuthor; filters: CgAuthorFilters; ordering: CgAuthorOrdering; create: CgAuthorCreate; update: CgAuthorUpdate; id: string };
  "cg_post": { row: CgPost; filters: CgPostFilters; ordering: CgPostOrdering; create: CgPostCreate; update: CgPostUpdate; id: number };
  "cg_ticket": { row: CgTicket; filters: CgTicketFilters; ordering: CgTicketOrdering; create: CgTicketCreate; update: CgTicketUpdate; id: string };
}

export interface UmbralOptions {
  /** Sent as `Authorization: Bearer <token>` on every request. */
  token?: string;
  /** Extra headers merged into every request. */
  headers?: Record<string, string>;
  /** Custom fetch (SSR / tests). Defaults to the global `fetch`. */
  fetch?: typeof fetch;
  /** Base path of the realtime plugin, for `.on(...)`. Defaults to "/realtime". */
  realtimePath?: string;
}

/** A live subscription started by `Umbral.on`. Call `close()` to stop it. */
export interface Subscription {
  close(): void;
}

/** Handlers for model-change events. Each receives the row your `expose(...)`
    projection carries (the id by default), so you know which row to refetch. */
export interface ModelEvents<Row> {
  created?(row: Row): void;
  updated?(row: Row): void;
  deleted?(row: Row): void;
}

/** Thrown when the API returns a non-2xx response. `body` is the parsed error. */
export class UmbralError extends Error {
  constructor(public status: number, public body: unknown) {
    super(`umbral: request failed with status ${status}`);
    this.name = "UmbralError";
  }
}

class Query<Row, Filters, Ordering> {
  private params = new URLSearchParams();
  constructor(private client: Umbral, private table: string) {}

  /** Field filters — keys and value types are specific to this model. */
  filter(f: Filters): this {
    for (const [k, v] of Object.entries(f as Record<string, unknown>)) {
      if (v === undefined) continue;
      this.params.set(k, Array.isArray(v) ? v.join(",") : String(v));
    }
    return this;
  }

  /** Full-text `?search=` across the model's searchable columns. */
  search(term: string): this { this.params.set("search", term); return this; }

  /** `?ordering=` — pass fields; prefix `-` for descending. */
  orderBy(...fields: Ordering[]): this {
    this.params.set("ordering", (fields as unknown as string[]).join(","));
    return this;
  }


  /** Sparse fieldset (`?fields=`) — fetch only these columns. */
  fields(...cols: string[]): this { this.params.set("fields", cols.join(",")); return this; }

  /** Fetch the list. */
  async list(): Promise<Paginated<Row>> {
    const qs = this.params.toString();
    const path = `/api/${this.table}/` + (qs ? `?${qs}` : "");
    return this.client._request<Paginated<Row>>("GET", path);
  }
}

/** A typed client for this app's REST API. `new Umbral("https://api.example.com")`. */
export class Umbral {
  private realtimePath: string;
  constructor(private baseUrl: string, private opts: UmbralOptions = {}) {
    this.baseUrl = baseUrl.replace(/\/+$/, "");
    this.realtimePath = (opts.realtimePath ?? "/realtime").replace(/\/+$/, "");
  }

  /** Subscribe to `created` / `updated` / `deleted` events for a model over the
      realtime stream. The model must be `expose(...)`-d to `group` on the server.
      `"post"` autocompletes to exposed tables; each handler gets a typed row.
      Returns a {@link Subscription} — call `close()` to unsubscribe. */
  on<K extends keyof UmbralResources>(
    table: K,
    handlers: ModelEvents<Partial<UmbralResources[K]["row"]>>,
    opts: { group: string },
  ): Subscription {
    void table; // present for the type layer; the group carries the model's events
    const url =
      `${this.baseUrl}${this.realtimePath}/sse?groups=` + encodeURIComponent(opts.group);
    const es = new EventSource(url, { withCredentials: true });
    const onEvent = (ev: MessageEvent) => {
      let env: { c?: string; e?: string; d?: unknown };
      try { env = JSON.parse(ev.data); } catch { return; }
      if (env.c !== opts.group) return;
      const cb = (handlers as Record<string, ((row: unknown) => void) | undefined>)[env.e ?? ""];
      if (cb) cb(env.d);
    };
    es.addEventListener("u", onEvent as EventListener);
    return { close: () => es.close() };
  }

  /** Start a query against a REST-exposed table. */
  from<K extends keyof UmbralResources>(
    table: K,
  ): Query<UmbralResources[K]["row"], UmbralResources[K]["filters"], UmbralResources[K]["ordering"]> {
    return new Query(this, table as string);
  }

  /** Retrieve one row by primary key. */
  get<K extends keyof UmbralResources>(table: K, id: UmbralResources[K]["id"]): Promise<UmbralResources[K]["row"]> {
    return this._request(`GET`, `/api/${table as string}/${id}/`);
  }

  /** Create a row. The body type omits server-managed fields; `noedit` fields
      are allowed here (settable on create). */
  create<K extends keyof UmbralResources>(
    table: K,
    data: UmbralResources[K]["create"],
  ): Promise<UmbralResources[K]["row"]> {
    return this._request(`POST`, `/api/${table as string}/`, data);
  }

  /** Partially update a row (PATCH). The body type excludes `noedit` fields. */
  update<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
    data: UmbralResources[K]["update"],
  ): Promise<UmbralResources[K]["row"]> {
    return this._request(`PATCH`, `/api/${table as string}/${id}/`, data);
  }

  /** Delete a row by primary key. */
  async delete<K extends keyof UmbralResources>(table: K, id: UmbralResources[K]["id"]): Promise<void> {
    await this._request(`DELETE`, `/api/${table as string}/${id}/`);
  }

  /** @internal */
  async _request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const doFetch = this.opts.fetch ?? fetch;
    const headers: Record<string, string> = { "Accept": "application/json", ...this.opts.headers };
    if (this.opts.token) headers["Authorization"] = `Bearer ${this.opts.token}`;
    const init: RequestInit = { method, headers };
    if (body !== undefined) {
      headers["Content-Type"] = "application/json";
      init.body = JSON.stringify(body);
    }
    const res = await doFetch(this.baseUrl + path, init);
    const parsed = res.status === 204 ? null : await res.json().catch(() => null);
    if (!res.ok) throw new UmbralError(res.status, parsed);
    return parsed as T;
  }
}
