// Code generated by `umbral gen-client`. DO NOT EDIT.
//
// client.d.ts — the types
//
// Regenerate after any model or REST-resource change:
//     cargo run -- gen-client --out <this directory>
//
// Base path: /api. Auth: Bearer token / apiKey (X-API-Key).

// Code generated by `umbral typegen`. DO NOT EDIT.
//
// Regenerate after any model change:
//     cargo run -- typegen --out <this file>
//
// These describe the JSON umbral puts on the wire: the model struct as serde
// serialises it. Field names are snake_case because the wire is snake_case.
// A `ForeignKey<T>` is the target's primary-key value, not a nested object.

/** `draft` = Draft, `published` = Published, `archived` = Archived */
export type CgPostStatus = "draft" | "published" | "archived";

/** Table `cg_author`, from the `app` plugin. */
export interface CgAuthor {
  slug: string;
  name: string;
}

/** Table `cg_post`, from the `app` plugin. */
export interface CgPost {
  id: number;
  title: string;
  body: string | null;
  status: CgPostStatus;
  views: number;
  /** Foreign key: the `slug` of a CgAuthor (`cg_author`). */
  author: string;
  slug: string;
  internal: string;
  created_at: string;
}

/** Table `cg_ticket`, from the `app` plugin. */
export interface CgTicket {
  id: string;
  subject: string;
}

/** Filterable query parameters for `cg_author`. Every key is optional and AND-combined server-side. */
export interface CgAuthorFilters {
  "name"?: string;
  "name__ne"?: string;
  "name__contains"?: string;
  "name__icontains"?: string;
  "name__startswith"?: string;
  "name__in"?: string[];
}
export type CgAuthorOrdering = "slug" | "-slug" | "name" | "-name";
/** Body for creating a `cg_author`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface CgAuthorCreate {
  name: string;
}
/** Body for updating a `cg_author` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface CgAuthorUpdate {
  name?: string;
}

/** Filterable query parameters for `cg_post`. Every key is optional and AND-combined server-side. */
export interface CgPostFilters {
  "title"?: string;
  "title__ne"?: string;
  "title__contains"?: string;
  "title__icontains"?: string;
  "title__startswith"?: string;
  "title__in"?: string[];
  "body"?: string;
  "body__ne"?: string;
  "body__contains"?: string;
  "body__icontains"?: string;
  "body__startswith"?: string;
  "body__in"?: string[];
  "body__isnull"?: boolean;
  "status"?: CgPostStatus;
  "status__ne"?: CgPostStatus;
  "status__contains"?: string;
  "status__icontains"?: string;
  "status__startswith"?: string;
  "status__in"?: CgPostStatus[];
  "views"?: number;
  "views__ne"?: number;
  "views__gte"?: number;
  "views__lte"?: number;
  "views__gt"?: number;
  "views__lt"?: number;
  "views__in"?: number[];
  "author"?: string;
  "author__ne"?: string;
  "author__in"?: string[];
  "slug"?: string;
  "slug__ne"?: string;
  "slug__contains"?: string;
  "slug__icontains"?: string;
  "slug__startswith"?: string;
  "slug__in"?: string[];
  "internal"?: string;
  "internal__ne"?: string;
  "internal__contains"?: string;
  "internal__icontains"?: string;
  "internal__startswith"?: string;
  "internal__in"?: string[];
  "created_at"?: string;
  "created_at__ne"?: string;
  "created_at__gte"?: string;
  "created_at__lte"?: string;
  "created_at__gt"?: string;
  "created_at__lt"?: string;
  "created_at__in"?: string[];
}
export type CgPostOrdering = "id" | "-id" | "title" | "-title" | "body" | "-body" | "status" | "-status" | "views" | "-views" | "author" | "-author" | "slug" | "-slug" | "internal" | "-internal" | "created_at" | "-created_at";
/** Body for creating a `cg_post`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface CgPostCreate {
  title: string;
  body?: string | null;
  status: CgPostStatus;
  views: number;
  author: string;
  slug: string;
}
/** Body for updating a `cg_post` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface CgPostUpdate {
  title?: string;
  body?: string | null;
  status?: CgPostStatus;
  views?: number;
  author?: string;
}

/** Filterable query parameters for `cg_ticket`. Every key is optional and AND-combined server-side. */
export interface CgTicketFilters {
  "subject"?: string;
  "subject__ne"?: string;
  "subject__contains"?: string;
  "subject__icontains"?: string;
  "subject__startswith"?: string;
  "subject__in"?: string[];
}
export type CgTicketOrdering = "id" | "-id" | "subject" | "-subject";
/** Body for creating a `cg_ticket`. Server-managed columns (id, auto-timestamps, privileged, no-form) are omitted. */
export interface CgTicketCreate {
  subject: string;
}
/** Body for updating a `cg_ticket` (PATCH; all fields optional). `noedit` columns are excluded — they can be set on create but not changed. */
export interface CgTicketUpdate {
  subject?: string;
}

/** A list response. `results` + `count` are always present; the rest depend on the paginator. */
export interface Paginated<T> {
  results: T[];
  count: number;
}

/** Maps each REST-exposed table to its row, filter, and ordering types. `Umbral.from` keys off this. */
export interface UmbralResources {
  "cg_author": { row: CgAuthor; filters: CgAuthorFilters; ordering: CgAuthorOrdering; create: CgAuthorCreate; update: CgAuthorUpdate; id: string };
  "cg_post": { row: CgPost; filters: CgPostFilters; ordering: CgPostOrdering; create: CgPostCreate; update: CgPostUpdate; id: number };
  "cg_ticket": { row: CgTicket; filters: CgTicketFilters; ordering: CgTicketOrdering; create: CgTicketCreate; update: CgTicketUpdate; id: string };
}

export interface UmbralOptions {
  /** Token sent as `Bearer <token>` in the `Authorization` header
      (the prefix comes from your API's declared security scheme). Override the
      prefix with `tokenPrefix` — e.g. an API that expects `Token <key>`. */
  token?: string;
  /** Overrides the `Authorization` prefix for `token`. Defaults to
      "Bearer", read from the security scheme. */
  tokenPrefix?: string;
  /** API key sent in the `X-API-Key` header (the header name comes from
      your API's declared apiKey scheme). Override with `apiKeyHeader`. */
  apiKey?: string;
  /** Overrides the header `apiKey` is sent in. Defaults to "X-API-Key",
      read from the security scheme. */
  apiKeyHeader?: string;
  /** Dynamic auth: called per request, its headers merged in last (they win).
      Use for a rotating JWT, a refresh flow, request signing — anything the
      static options above can't express. */
  getAuthHeaders?: () => Record<string, string> | Promise<Record<string, string>>;
  /** Extra static headers merged into every request. */
  headers?: Record<string, string>;
  /** `fetch` credentials mode (cookies). Defaults to undefined. */
  credentials?: RequestCredentials;
  /** Custom fetch (SSR / tests). Defaults to the global `fetch`. */
  fetch?: typeof fetch;
  /** Base path of the realtime plugin, for `.on(...)`. Defaults to "/realtime". */
  realtimePath?: string;
}

/** A live subscription started by `Umbral.on`. Call `close()` to stop it. */
export interface Subscription {
  close(): void;
}

/** Handlers for model-change events. Each receives the row your `expose(...)`
    projection carries (the id by default), so you know which row to refetch. */
export interface ModelEvents<Row> {
  created?(row: Row): void;
  updated?(row: Row): void;
  deleted?(row: Row): void;
}

/** Thrown when the API returns a non-2xx response. `body` is the parsed error. */
export declare class UmbralError extends Error {
  readonly status: number;
  readonly body: unknown;
  constructor(status: number, body: unknown);
}

/** A list query. Keys and value types are specific to the model it came from. */
export declare class Query<Row, Filters, Ordering> {
  /** Field filters — the keys are exactly the (field, lookup) pairs this model accepts. */
  filter(f: Filters): this;
  /** Full-text `?search=` across the model's searchable columns. */
  search(term: string): this;
  /** `?ordering=` — pass fields; prefix `-` for descending. */
  orderBy(...fields: Ordering[]): this;

  /** Set any raw query param — the escape hatch for params the typed methods don't cover. */
  param(key: string, value: string | number | boolean): this;
  /** Sparse fieldset (`?fields=`) — fetch only these columns. */
  fields(...cols: string[]): this;
  /** Fetch the list. */
  list(): Promise<Paginated<Row>>;
}

/** A typed client for this app's REST API. */
export declare class Umbral {
  constructor(baseUrl: string, opts?: UmbralOptions);

  /** Start a query against a REST-exposed table. */
  from<K extends keyof UmbralResources>(
    table: K,
  ): Query<UmbralResources[K]["row"], UmbralResources[K]["filters"], UmbralResources[K]["ordering"]>;

  /** Retrieve one row by primary key. */
  get<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Create a row. The body type omits server-managed fields; `noedit` fields
      are allowed here (settable on create). */
  create<K extends keyof UmbralResources>(
    table: K,
    data: UmbralResources[K]["create"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Partially update a row (PATCH). The body type excludes `noedit` fields. */
  update<K extends keyof UmbralResources>(
    table: K,
    id: UmbralResources[K]["id"],
    data: UmbralResources[K]["update"],
  ): Promise<UmbralResources[K]["row"]>;

  /** Delete a row by primary key. */
  delete<K extends keyof UmbralResources>(table: K, id: UmbralResources[K]["id"]): Promise<void>;

  /** Subscribe to `created` / `updated` / `deleted` for a model, over the
      realtime plugin's shared connection (one SSE stream across all tabs). The
      model must be `expose(...)`-d to `group` on the server. */
  on<K extends keyof UmbralResources>(
    table: K,
    handlers: ModelEvents<Partial<UmbralResources[K]["row"]>>,
    opts: { group: string },
  ): Subscription;
}
