// Code generated by `umbral typegen`. DO NOT EDIT.
//
// Regenerate after any model change:
//     cargo run -- typegen --out <this file>
//
// These describe the JSON umbral puts on the wire: the model struct as serde
// serialises it. Field names are snake_case because the wire is snake_case.
// A `ForeignKey<T>` is the target's primary-key value, not a nested object.

/** `draft` = Draft, `published` = Published, `archived` = Archived */
export type CgPostStatus = "draft" | "published" | "archived";

/** Table `cg_author`, from the `app` plugin. */
export interface CgAuthor {
  slug: string;
  name: string;
}

/** Table `cg_post`, from the `app` plugin. */
export interface CgPost {
  id: number;
  title: string;
  body: string | null;
  status: CgPostStatus;
  views: number;
  /** Foreign key: the `slug` of a CgAuthor (`cg_author`). */
  author: string;
  slug: string;
  internal: string;
  created_at: string;
}

/** Table `cg_ticket`, from the `app` plugin. */
export interface CgTicket {
  id: string;
  subject: string;
}
