//! EcommercePlugin — generated by `umbral startapp ecommerce`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(ecommerce::EcommercePlugin::default())
//! ```

pub mod models;

use umbral::migrate::ModelMeta;
use umbral::plugin::Plugin;

#[derive(Debug, Default, Clone)]
pub struct EcommercePlugin;

impl Plugin for EcommercePlugin {
    fn name(&self) -> &'static str {
        "ecommerce"
    }

    fn dependencies(&self) -> &'static [&'static str] {
        &["content"]
    }

    fn models(&self) -> Vec<ModelMeta> {
        // Every #[derive(Model)] in THIS crate, via the link-time registry
        // (gaps4 #40) — replaces 16 hand-listed ModelMeta::for_::<T>()
        // lines that had to be kept in sync with models.rs by hand.
        umbral::discovered_models!()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use umbral::plugin::Plugin;

    /// gaps4 #40 proof: `discovered_models!()` finds every #[derive(Model)]
    /// in THIS crate (16 of them, across the models submodule) at link
    /// time — the replacement for the hand-listed vec must not silently
    /// under-count, which would make makemigrations try to DROP tables.
    #[test]
    fn discovered_models_finds_all_sixteen() {
        let tables: std::collections::BTreeSet<String> = EcommercePlugin
            .models()
            .into_iter()
            .map(|m| m.table)
            .collect();
        assert_eq!(
            tables.len(),
            16,
            "ecommerce owns 16 models; discovery found: {tables:?}"
        );
        // Spot-check a submodule model and an M2M-join model.
        assert!(tables.contains("product"));
        assert!(tables.contains("coupon_product"));
    }
}
