//! EcommercePlugin — generated by `umbra startapp ecommerce`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(ecommerce::EcommercePlugin::default())
//! ```

pub mod models;

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct EcommercePlugin;

impl Plugin for EcommercePlugin {
    fn name(&self) -> &'static str {
        "ecommerce"
    }

    fn dependencies(&self) -> &'static [&'static str] {
        &["content"]
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![
            ModelMeta::for_::<models::Brand>(),
            ModelMeta::for_::<models::Product>(),
            ModelMeta::for_::<models::ProductImage>(),
            ModelMeta::for_::<models::ProductVariant>(),
            ModelMeta::for_::<models::Customer>(),
            ModelMeta::for_::<models::Address>(),
            ModelMeta::for_::<models::Order>(),
            ModelMeta::for_::<models::OrderItem>(),
            ModelMeta::for_::<models::Payment>(),
            ModelMeta::for_::<models::Shipment>(),
            ModelMeta::for_::<models::Coupon>(),
            ModelMeta::for_::<models::Review>(),
            ModelMeta::for_::<models::ProductTag>(),
            ModelMeta::for_::<models::CouponProduct>(),
            ModelMeta::for_::<models::CouponCategory>(),
            ModelMeta::for_::<models::ReviewImage>(),
        ]
    }

    fn routes(&self) -> Router {
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
