//! ShowcasePlugin — generated by `umbra startapp showcase`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(showcase::ShowcasePlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

pub use models::{
    ShowcaseDatabase, ShowcaseDeployment, ShowcaseEntry, ShowcaseProjectType, ShowcaseStatus,
};

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct ShowcasePlugin;

impl Plugin for ShowcasePlugin {
    fn name(&self) -> &'static str {
        "showcase"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![ModelMeta::for_::<models::ShowcaseEntry>()]
    }

    fn routes(&self) -> Router {
        // Add your routes here. The base path is up to you — convention
        // is `/<name>/...` for HTML and `/api/<name>/...` for JSON.
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
