//! Smoke test for the build pipeline. Asserts the build script
//! ran and `OUT_DIR/generated_assets.rs` was included into the
//! crate. Does NOT exercise HTTP — that's a later milestone.
//!
//! The `CSS` and `JS` constants generated by `build.rs` are
//! `pub(crate)`, so this test can't import them directly. The
//! `PlaygroundPlugin` type and the `Plugin` trait are `pub`, and
//! the `Plugin::routes` impl references both constants internally —
//! so calling `default()` and `name()` is enough to force the
//! generated module to be evaluated. If `include!` failed at compile
//! time, this file would not compile.

#![allow(dead_code, private_interfaces)]

use umbral::prelude::*;
use umbral_playground::PlaygroundPlugin;

#[test]
fn build_pipeline_runs() {
    // Compiles only if `OUT_DIR/generated_assets.rs` was included
    // and defines both `JS` and `CSS` constants. The `Plugin` trait
    // impl on `PlaygroundPlugin` references both internally, so
    // constructing the plugin is enough to force the generated
    // module to be evaluated. If `include!` failed, this file
    // would not compile.
    let plugin = PlaygroundPlugin::default();
    assert_eq!(plugin.name(), "umbral-playground");
}
