//! AccountsPlugin — generated by `umbra startapp accounts`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(accounts::AccountsPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

pub use models::{
    GitHubAccount, GitHubAccountStatus, TrustGateCheck, TrustGateKind, TrustGateStatus,
    WebsiteProfile,
};

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::routes::Routes;
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct AccountsPlugin;

impl Plugin for AccountsPlugin {
    fn name(&self) -> &'static str {
        "accounts"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![
            ModelMeta::for_::<models::WebsiteProfile>(),
            ModelMeta::for_::<models::GitHubAccount>(),
            ModelMeta::for_::<models::TrustGateCheck>(),
        ]
    }

    fn routes(&self) -> Router {
        // Add your routes here. The base path is up to you — convention
        // is `/<name>/...` for HTML and `/api/<name>/...` for JSON.
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
