// Code generated by `umbral typegen`. DO NOT EDIT.
//
// Regenerate after any model change:
//     cargo run -- typegen --out <this file>
//
// These describe the JSON umbral puts on the wire: the model struct as serde
// serialises it. Field names are snake_case because the wire is snake_case.
// A `ForeignKey<T>` is the target's primary-key value, not a nested object.

/** `billing` = Billing, `shipping` = Shipping */
export type AddressKind = "billing" | "shipping";

/** `new` = New, `read` = Read, `replied` = Replied, `closed` = Closed */
export type ContactMessageStatus = "new" | "read" | "replied" | "closed";

/** `percentage` = Percentage, `fixed_amount` = FixedAmount, `free_shipping` = FreeShipping */
export type CouponDiscountType = "percentage" | "fixed_amount" | "free_shipping";

/** `usd` = Usd, `eur` = Eur, `gbp` = Gbp, `kes` = Kes */
export type OrderCurrency = "usd" | "eur" | "gbp" | "kes";

/** `pending` = Pending, `authorized` = Authorized, `captured` = Captured, `failed` = Failed, `refunded` = Refunded */
export type OrderPaymentStatus = "pending" | "authorized" | "captured" | "failed" | "refunded";

/** `pending` = Pending, `paid` = Paid, `fulfilled` = Fulfilled, `shipped` = Shipped, `delivered` = Delivered, `cancelled` = Cancelled, `refunded` = Refunded */
export type OrderStatus = "pending" | "paid" | "fulfilled" | "shipped" | "delivered" | "cancelled" | "refunded";

/** `default` = Default, `full_width` = FullWidth, `landing` = Landing */
export type PageTemplate = "default" | "full_width" | "landing";

/** `usd` = Usd, `eur` = Eur, `gbp` = Gbp, `kes` = Kes */
export type PaymentCurrency = "usd" | "eur" | "gbp" | "kes";

/** `card` = Card, `mpesa` = Mpesa, `paypal` = Paypal, `banktransfer` = BankTransfer, `cod` = Cod */
export type PaymentMethod = "card" | "mpesa" | "paypal" | "banktransfer" | "cod";

/** `pending` = Pending, `authorized` = Authorized, `captured` = Captured, `failed` = Failed, `refunded` = Refunded */
export type PaymentStatus = "pending" | "authorized" | "captured" | "failed" | "refunded";

/** `draft` = Draft, `published` = Published, `scheduled` = Scheduled */
export type PostStatus = "draft" | "published" | "scheduled";

/** `usd` = Usd, `eur` = Eur, `gbp` = Gbp, `kes` = Kes */
export type ProductCurrency = "usd" | "eur" | "gbp" | "kes";

/** `draft` = Draft, `active` = Active, `archived` = Archived */
export type ProductStatus = "draft" | "active" | "archived";

/** `moved_permanently` = MovedPermanently, `found` = Found */
export type RedirectCode = "moved_permanently" | "found";

/** Table `address`, from the `app` plugin. */
export interface Address {
  id: number;
  /** Foreign key: the `id` of a Customer (`customer`). */
  customer: number;
  kind: AddressKind;
  line1: string;
  line2: string | null;
  city: string;
  region: string | null;
  postal_code: string;
  country: string;
  is_default: boolean;
}

/**
 * User preference
 * Table `admin_user_pref`, from the `app` plugin.
 */
export interface AdminUserPref {
  id: number;
  user_id: number;
  theme: string;
  density: string;
  sidebar_collapsed: boolean;
  dashboard_layout: string;
  preferences: string | null;
  updated_at: string;
}

/** Table `auth_challenge`, from the `app` plugin. */
export interface AuthChallenge {
  id: number;
  /** Foreign key into `auth_user`. */
  user_id: number;
  purpose: string;
  secret_hash: string;
  expires_at: string;
  attempts: number;
  used_at: string | null;
  created_at: string;
}

/** Table `auth_token`, from the `app` plugin. */
export interface AuthToken {
  id: number;
  /** Foreign key into `auth_user`. */
  user_id: number;
  key_hash: string;
  name: string;
  created_at: string;
  last_used_at: string | null;
}

/** Table `banner`, from the `app` plugin. */
export interface Banner {
  id: number;
  title: string;
  content: string | null;
  image: string | null;
  link_url: string | null;
  starts_at: string | null;
  ends_at: string | null;
  position: number;
  is_active: boolean;
}

/** Table `brand`, from the `app` plugin. */
export interface Brand {
  id: number;
  name: string;
  slug: string;
  logo: string | null;
  website: string | null;
  description: string | null;
}

/** Table `category`, from the `app` plugin. */
export interface Category {
  id: number;
  slug: string;
  name: string;
  description: string | null;
  image: string | null;
  /** Foreign key: the `id` of a Category (`category`). */
  parent: number | null;
  position: number;
  is_active: boolean;
  test_field: string | null;
}

/** Table `comment`, from the `app` plugin. */
export interface Comment {
  id: number;
  /** Foreign key: the `id` of a Post (`post`). */
  post: number;
  /** Foreign key: the `id` of a Comment (`comment`). */
  parent: number | null;
  /** Foreign key into `auth_user`. */
  author: number | null;
  author_name: string | null;
  author_email: string | null;
  body: string;
  is_approved: boolean;
  created_at: string;
}

/** Table `contact_message`, from the `app` plugin. */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone: string | null;
  subject: string;
  message: string;
  status: ContactMessageStatus;
  ip_address: string | null;
  created_at: string;
}

/** Table `coupon`, from the `app` plugin. */
export interface Coupon {
  id: number;
  code: string;
  discount_type: CouponDiscountType;
  value: string;
  valid_from: string;
  valid_to: string;
  usage_limit: number | null;
  used_count: number;
  is_active: boolean;
}

/** Table `coupon_category`, from the `app` plugin. */
export interface CouponCategory {
  id: number;
  /** Foreign key: the `id` of a Coupon (`coupon`). */
  coupon: number;
  /** Foreign key: the `id` of a Category (`category`). */
  category: number;
}

/** Table `coupon_product`, from the `app` plugin. */
export interface CouponProduct {
  id: number;
  /** Foreign key: the `id` of a Coupon (`coupon`). */
  coupon: number;
  /** Foreign key: the `id` of a Product (`product`). */
  product: number;
}

/** Table `customer`, from the `app` plugin. */
export interface Customer {
  id: number;
  /** Foreign key into `auth_user`. */
  user: number;
  phone: string | null;
  date_of_birth: string | null;
  accepts_marketing: boolean;
  loyalty_points: number;
  created_at: string;
  updated_at: string;
}

/** Table `faq`, from the `app` plugin. */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category: string | null;
  position: number;
  is_published: boolean;
}

/** Table `media_asset`, from the `app` plugin. */
export interface MediaAsset {
  id: number;
  file: string;
  title: string | null;
  alt_text: string | null;
  folder: string | null;
  mime: string;
  size_bytes: number;
  /** Foreign key into `auth_user`. */
  uploaded_by: number | null;
  created_at: string;
}

/** Table `menu`, from the `app` plugin. */
export interface Menu {
  id: number;
  name: string;
  slug: string;
}

/** Table `menu_item`, from the `app` plugin. */
export interface MenuItem {
  id: number;
  /** Foreign key: the `id` of a Menu (`menu`). */
  menu: number;
  /** Foreign key: the `id` of a MenuItem (`menu_item`). */
  parent: number | null;
  label: string;
  url: string | null;
  /** Foreign key: the `id` of a Page (`page`). */
  page: number | null;
  position: number;
  target: string;
  is_active: boolean;
}

/** Table `note`, from the `app` plugin. */
export interface Note {
  id: number;
  title: string;
  description: string;
}

/**
 * Object permissions
 * Table `permissions_objectpermission`, from the `app` plugin.
 */
export interface ObjectPermission {
  id: number;
  user_id: string;
  /** Foreign key into `permissions_permission`. */
  permission_id: number;
  object_pk: string;
}

/** Table `order`, from the `app` plugin. */
export interface Order {
  id: number;
  number: string;
  public_id: string;
  /** Foreign key: the `id` of a Customer (`customer`). */
  customer: number;
  status: OrderStatus;
  payment_status: OrderPaymentStatus;
  currency: OrderCurrency;
  subtotal: string;
  shipping_total: string;
  tax_total: string;
  discount_total: string;
  grand_total: string;
  /** Foreign key: the `id` of a Coupon (`coupon`). */
  coupon: number | null;
  /** Foreign key: the `id` of a Address (`address`). */
  shipping_address: number | null;
  /** Foreign key: the `id` of a Address (`address`). */
  billing_address: number | null;
  notes: string | null;
  invoice: string | null;
  placed_at: string;
  updated_at: string;
}

/** Table `order_item`, from the `app` plugin. */
export interface OrderItem {
  id: number;
  /** Foreign key: the `id` of a Order (`order`). */
  order: number;
  /** Foreign key: the `id` of a Product (`product`). */
  product: number;
  /** Foreign key: the `id` of a ProductVariant (`product_variant`). */
  variant: number | null;
  quantity: number;
  unit_price: string;
  line_total: string;
}

/** Table `page`, from the `app` plugin. */
export interface Page {
  id: number;
  slug: string;
  title: string;
  content: string;
  template: PageTemplate;
  /** Foreign key: the `id` of a Page (`page`). */
  parent: number | null;
  position: number;
  is_published: boolean;
  seo_title: string | null;
  seo_description: string | null;
  published_at: string | null;
  updated_at: string;
}

/** Table `payment`, from the `app` plugin. */
export interface Payment {
  id: number;
  /** Foreign key: the `id` of a Order (`order`). */
  order: number;
  method: PaymentMethod;
  status: PaymentStatus;
  amount: string;
  currency: PaymentCurrency;
  transaction_id: string | null;
  paid_at: string | null;
}

/** Table `post`, from the `app` plugin. */
export interface Post {
  id: number;
  slug: string;
  title: string;
  excerpt: string | null;
  body: string;
  status: PostStatus;
  /** Foreign key into `auth_user`. */
  author: number;
  /** Foreign key: the `id` of a Category (`category`). */
  category: number | null;
  cover_image: string | null;
  attachment: string | null;
  is_featured: boolean;
  reading_minutes: number;
  view_count: number;
  seo_title: string | null;
  seo_description: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
  /** Many-to-many. The related rows when the query used `.prefetch_related(...)`; `[]` otherwise. */
  tags: Tag[];
}

/** Table `product`, from the `app` plugin. */
export interface Product {
  id: number;
  sku: string;
  slug: string;
  name: string;
  description: string;
  status: ProductStatus;
  /** Foreign key: the `id` of a Category (`category`). */
  category: number;
  /** Foreign key: the `id` of a Brand (`brand`). */
  brand: number | null;
  price: string;
  compare_at_price: string | null;
  currency: ProductCurrency;
  tax_rate: string;
  stock_quantity: number;
  weight_kg: number | null;
  dimensions: unknown | null;
  barcode: string | null;
  thumbnail: string | null;
  spec_sheet: string | null;
  is_featured: boolean;
  rating_avg: number;
  review_count: number;
  metadata: unknown;
  keywords: string | null;
  external_id: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

/** Table `product_image`, from the `app` plugin. */
export interface ProductImage {
  id: number;
  /** Foreign key: the `id` of a Product (`product`). */
  product: number;
  image: string;
  alt_text: string | null;
  position: number;
}

/** Table `product_tag`, from the `app` plugin. */
export interface ProductTag {
  id: number;
  /** Foreign key: the `id` of a Product (`product`). */
  product: number;
  /** Foreign key: the `id` of a Tag (`tag`). */
  tag: number;
}

/** Table `product_variant`, from the `app` plugin. */
export interface ProductVariant {
  id: number;
  /** Foreign key: the `id` of a Product (`product`). */
  product: number;
  sku: string;
  attributes: unknown;
  price_override: string | null;
  stock_quantity: number;
}

/** Table `redirect`, from the `app` plugin. */
export interface Redirect {
  id: number;
  from_path: string;
  to_path: string;
  code: RedirectCode;
  is_active: boolean;
  hits: number;
}

/** Table `review`, from the `app` plugin. */
export interface Review {
  id: number;
  /** Foreign key: the `id` of a Product (`product`). */
  product: number;
  /** Foreign key: the `id` of a Customer (`customer`). */
  customer: number;
  rating: number;
  title: string | null;
  body: string;
  is_verified_purchase: boolean;
  is_approved: boolean;
  created_at: string;
}

/** Table `review_image`, from the `app` plugin. */
export interface ReviewImage {
  id: number;
  /** Foreign key: the `id` of a Review (`review`). */
  review: number;
  image: string;
}

/** Table `shipment`, from the `app` plugin. */
export interface Shipment {
  id: number;
  /** Foreign key: the `id` of a Order (`order`). */
  order: number;
  carrier: string;
  tracking_number: string | null;
  shipped_at: string | null;
  delivered_at: string | null;
}

/** Table `site_setting`, from the `app` plugin. */
export interface SiteSetting {
  id: number;
  site_name: string;
  tagline: string | null;
  logo: string | null;
  favicon: string | null;
  contact_email: string;
  social_links: unknown;
  default_seo: unknown;
  config: unknown;
}

/** Table `subscriber`, from the `app` plugin. */
export interface Subscriber {
  id: number;
  email: string;
  is_confirmed: boolean;
  confirmed_at: string | null;
  source: string | null;
  created_at: string;
}

/** Table `tag`, from the `app` plugin. */
export interface Tag {
  id: number;
  name: string;
  slug: string;
}

/** Table `testimonial`, from the `app` plugin. */
export interface Testimonial {
  id: number;
  author_name: string;
  author_title: string | null;
  avatar: string | null;
  quote: string;
  rating: number | null;
  is_featured: boolean;
  position: number;
}
