//! gaps3 #38 — TypeScript types generated from the model registry.
//!
//! These drive `typegen::typescript_for` with `ModelMeta::for_::<T>()` off real
//! `#[derive(Model)]` types, so the whole derive → registry → generator path is
//! under test rather than a hand-built metadata fixture. A hand-built fixture
//! covers the exotic column types no test model wants to carry.
//!
//! `typescript_for` is pure — no registry, no pool, no `App::build()` — so every
//! case lives in one binary.

use umbral::migrate::{Column, ModelMeta};
use umbral::orm::{ArrayElement, ForeignKey, M2M, SqlType};
use umbral::typegen::typescript_for;
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Models. `TgAuthor` has a String primary key on purpose: an FK is the target's
// PK *value*, so `TgPost.author` must type as `string`, not `number`.
// ---------------------------------------------------------------------------

#[derive(
    Debug,
    Default,
    Clone,
    Copy,
    PartialEq,
    Eq,
    umbral::orm::Choices,
    serde::Serialize,
    serde::Deserialize,
)]
#[choices(rename_all = "lowercase")]
pub enum TgStatus {
    #[default]
    Draft,
    Published,
    Archived,
}

#[derive(Debug, Clone, sqlx::FromRow, serde::Serialize, serde::Deserialize, umbral::orm::Model)]
#[umbral(table = "tg_tag")]
pub struct TgTag {
    pub id: i64,
    pub name: String,
}

#[derive(Debug, Clone, sqlx::FromRow, serde::Serialize, serde::Deserialize, umbral::orm::Model)]
#[umbral(table = "tg_author")]
pub struct TgAuthor {
    #[umbral(primary_key)]
    pub slug: String,
    pub email: String,
}

#[derive(Debug, Clone, sqlx::FromRow, serde::Serialize, serde::Deserialize, umbral::orm::Model)]
#[umbral(table = "tg_post")]
pub struct TgPost {
    pub id: i64,
    #[umbral(help = "Shown in the browser tab.")]
    pub title: String,
    pub body: Option<String>,
    #[umbral(no_reverse)]
    pub author: ForeignKey<TgAuthor>,
    #[umbral(choices)]
    pub status: TgStatus,
    pub views: i32,
    pub score: Option<f64>,
    pub public_id: Uuid,
    pub published_at: Option<chrono::DateTime<chrono::Utc>>,
    #[umbral(m2m = "tg_tag")]
    pub tags: M2M<TgTag>,
}

fn generated() -> String {
    typescript_for(&[
        ModelMeta::for_::<TgAuthor>(),
        ModelMeta::for_::<TgPost>(),
        ModelMeta::for_::<TgTag>(),
    ])
}

/// Assert `needle` appears, with the whole file in the failure message — a
/// generator test that says `assert!(false)` teaches nothing.
#[track_caller]
fn assert_contains(haystack: &str, needle: &str) {
    assert!(
        haystack.contains(needle),
        "expected to find:\n  {needle}\nin generated output:\n{haystack}",
    );
}

// ---------------------------------------------------------------------------

/// A plain model becomes an exported interface with its columns in declaration
/// order, and the header warns the file is generated.
#[test]
fn scalar_columns_map_to_typescript_primitives() {
    let ts = generated();

    assert_contains(&ts, "// Code generated by `umbral typegen`. DO NOT EDIT.");
    assert_contains(&ts, "export interface TgTag {");
    assert_contains(&ts, "  id: number;");
    assert_contains(&ts, "  name: string;");
    // i32 and f64 both narrow to `number`; JS has one numeric type.
    assert_contains(&ts, "  views: number;");
    // Uuid crosses the wire as its hyphenated string form.
    assert_contains(&ts, "  public_id: string;");
}

/// `Option<T>` is the only route to SQL NULL in umbral, so it is the only route
/// to `| null` here. A non-null column must never gain it.
#[test]
fn optional_columns_become_nullable_unions() {
    let ts = generated();

    assert_contains(&ts, "  body: string | null;");
    assert_contains(&ts, "  score: number | null;");
    // chrono DateTime<Utc> is an RFC 3339 string on the wire.
    assert_contains(&ts, "  published_at: string | null;");

    assert!(
        !ts.contains("  title: string | null;"),
        "a non-nullable column must not be typed nullable:\n{ts}",
    );
}

/// The case that makes this worth generating rather than hand-writing: an FK is
/// the *target's primary-key value*. `TgAuthor` is keyed by a `String` slug, so
/// `TgPost.author` is a `string`. Hand-written clients get this wrong — the
/// author of gaps3 #38 watched `total_amount`, `match_no` and `username` each
/// pay the drift tax twice.
#[test]
fn foreign_key_types_as_the_targets_primary_key() {
    let ts = generated();

    assert_contains(&ts, "  author: string;");
    // `TgAuthor` keys on `slug`, not `id` — the comment must say so.
    assert_contains(&ts, "Foreign key: the `slug` of a TgAuthor (`tg_author`).");

    assert!(
        !ts.contains("  author: number;"),
        "an FK to a String-PK model must not be typed `number`:\n{ts}",
    );
}

/// An FK whose target is absent from the model list has no resolvable PK type.
/// It falls back to `number` — the historical `i64` default, matching
/// `migrate::fk_effective_type` — and the doc comment names the raw table
/// rather than inventing a model name.
#[test]
fn foreign_key_to_an_unlisted_target_falls_back_to_number() {
    let ts = typescript_for(&[ModelMeta::for_::<TgPost>()]);

    assert_contains(&ts, "  author: number;");
    assert_contains(&ts, "Foreign key into `tg_author`.");
}

/// `#[umbral(choices)]` becomes a string-literal union, so a typo'd status
/// fails at `tsc` instead of round-tripping to a 400.
#[test]
fn choices_become_a_string_literal_union() {
    let ts = generated();

    assert_contains(
        &ts,
        r#"export type TgPostStatus = "draft" | "published" | "archived";"#,
    );
    assert_contains(&ts, "  status: TgPostStatus;");
}

/// `M2M<T>` serialises as the full related rows (`[]` when the query did not
/// prefetch), so it types as `T[]`, not as an array of ids.
#[test]
fn m2m_fields_type_as_an_array_of_the_related_model() {
    let ts = generated();

    assert_contains(&ts, "  tags: TgTag[];");
    assert_contains(&ts, "`.prefetch_related(...)`");
}

/// `#[umbral(help = "...")]` is the field's documentation everywhere else in
/// umbral (admin, OpenAPI `description`); it should reach the frontend too.
#[test]
fn help_text_becomes_a_tsdoc_comment() {
    assert_contains(&generated(), "/** Shown in the browser tab. */");
}

/// Same models in, same bytes out. A generated file that reorders itself makes
/// every regeneration a diff, and CI can't check it in.
#[test]
fn output_is_deterministic() {
    assert_eq!(generated(), generated());
}

// ---------------------------------------------------------------------------
// Exotic column types, via a hand-built ModelMeta.
// ---------------------------------------------------------------------------

fn column(name: &str, ty: SqlType) -> Column {
    Column {
        name: name.to_string(),
        ty,
        ..Column::default()
    }
}

fn exotic() -> String {
    typescript_for(&[ModelMeta {
        name: "Exotic".to_string(),
        table: "exotic".to_string(),
        app_label: "app".to_string(),
        fields: vec![
            column("id", SqlType::BigInt),
            column("price", SqlType::Decimal),
            column("payload", SqlType::Json),
            column("blob", SqlType::Bytes),
            column("labels", SqlType::Array(ArrayElement::Text)),
            column("sizes", SqlType::Array(ArrayElement::Integer)),
            column("flag", SqlType::Boolean),
        ],
        ..ModelMeta::default()
    }])
}

/// Decimal is a string on the wire because a JSON number loses precision, and
/// `umbral-openapi` already says so (`format: decimal`). The two generators
/// describe the same bytes; disagreeing would be worse than shipping neither.
#[test]
fn decimal_is_a_string_and_says_why() {
    let ts = exotic();

    assert_contains(&ts, "  price: string;");
    assert_contains(&ts, "would lose precision");
}

/// A JSON column holds any JSON value. `unknown`, not `any`: the consumer has
/// to narrow it, which is the entire point of generating types.
#[test]
fn json_is_unknown_not_any() {
    let ts = exotic();

    assert_contains(&ts, "  payload: unknown;");
    assert!(!ts.contains(": any;"), "`any` defeats the purpose:\n{ts}");
}

/// Arrays recurse into their element type; BYTEA is a JSON array of bytes,
/// which is what umbral-rest actually emits.
#[test]
fn arrays_recurse_and_bytes_is_a_number_array() {
    let ts = exotic();

    assert_contains(&ts, "  labels: string[];");
    assert_contains(&ts, "  sizes: number[];");
    assert_contains(&ts, "  blob: number[];");
    assert_contains(&ts, "  flag: boolean;");
}

/// A multichoice column carries a comma-separated *subset* of its choices in
/// one string, so `"a" | "b"` would reject the legal value `"a,b"`. It stays a
/// plain `string`, matching umbral-openapi's refusal to emit an `enum` for it.
#[test]
fn multichoice_stays_a_plain_string() {
    let mut col = column("perms", SqlType::Text);
    col.choices = vec!["read".to_string(), "write".to_string()];
    col.is_multichoice = true;

    let ts = typescript_for(&[ModelMeta {
        name: "Grant".to_string(),
        table: "grant".to_string(),
        app_label: "app".to_string(),
        fields: vec![column("id", SqlType::BigInt), col],
        ..ModelMeta::default()
    }]);

    assert_contains(&ts, "  perms: string;");
    assert!(
        !ts.contains("export type GrantPerms"),
        "a multichoice column must not emit a union:\n{ts}",
    );
}

/// A choice value containing a quote must not break out of the string literal.
#[test]
fn choice_values_are_escaped() {
    let mut col = column("kind", SqlType::Text);
    col.choices = vec![r#"say"hi"#.to_string(), r"back\slash".to_string()];

    let ts = typescript_for(&[ModelMeta {
        name: "Quoted".to_string(),
        table: "quoted".to_string(),
        app_label: "app".to_string(),
        fields: vec![column("id", SqlType::BigInt), col],
        ..ModelMeta::default()
    }]);

    assert_contains(&ts, r#""say\"hi" | "back\\slash""#);
}
