//! FeaturesPlugin — generated by `umbra startapp features`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(features::FeaturesPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

pub use models::{
    FeatureCategory, FeatureMaturity, FeatureStatus, FeatureStatusEvent, FrameworkFeature,
};

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct FeaturesPlugin;

impl Plugin for FeaturesPlugin {
    fn name(&self) -> &'static str {
        "features"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![
            ModelMeta::for_::<models::FeatureCategory>(),
            ModelMeta::for_::<models::FrameworkFeature>(),
            ModelMeta::for_::<models::FeatureStatusEvent>(),
        ]
    }

    fn routes(&self) -> Router {
        // Add your routes here. The base path is up to you — convention
        // is `/<name>/...` for HTML and `/api/<name>/...` for JSON.
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
