/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    '../templates/**/*.html',
    '../src/**/*.rs',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest':   'var(--surface-container-lowest)',
        'surface-container-low':      'var(--surface-container-low)',
        'surface-container':          'var(--surface-container)',
        'surface-container-high':     'var(--surface-container-high)',
        'surface-container-highest':  'var(--surface-container-highest)',
        'surface-bright':             'var(--surface-bright)',
        'surface-dim':                'var(--surface-dim)',
        'surface':                    'var(--surface)',
        'surface-variant':            'var(--surface-variant)',
        'surface-tint':               'var(--surface-tint)',
        'on-surface':                 'var(--on-surface)',
        'on-surface-variant':         'var(--on-surface-variant)',
        'inverse-surface':            'var(--inverse-surface)',
        'inverse-on-surface':         'var(--inverse-on-surface)',
        'outline':                    'var(--outline)',
        'outline-variant':            'var(--outline-variant)',
        'background':                 'var(--background)',
        'on-background':              'var(--on-background)',
        'primary':                    'var(--primary)',
        'on-primary':                 'var(--on-primary)',
        'primary-container':          'var(--primary-container)',
        'on-primary-container':       'var(--on-primary-container)',
        'error':                      'var(--error)',
        'on-error':                   'var(--on-error)',
        'error-container':            'var(--error-container)',
        'on-error-container':         'var(--on-error-container)',
      },
      spacing: {
        'sidebar-width':     '260px',
        'sidebar-collapsed': '68px',
        'topbar-height':     '56px',
        'gutter':            '20px',
        'base': '4px',
        'xs':   '4px',
        'sm':   '8px',
        'md':   '16px',
        'lg':   '24px',
        'xl':   '32px',
      },
    },
  },
  plugins: [],
};
