//! Generate TypeScript types from the model registry.
//!
//! You declared your data once. Every frontend that talks to the app then
//! re-declares it by hand — a `Post` interface, a `PostStatus` union, an `author`
//! that is a `number` because someone remembered it was an FK. That copy drifts
//! on every field change, and the compiler on neither side can see the drift.
//! gaps3 #38 names this the single biggest ongoing tax on an umbral app with a
//! real frontend.
//!
//! So the models emit the types:
//!
//! ```bash
//! cargo run -- typegen --out web/src/api/models.ts
//! ```
//!
//! The output is derived from [`ModelMeta`] — the same registry the ORM, the
//! migration engine, the admin, and umbral-rest read — so it cannot describe a
//! shape the database doesn't have.
//!
//! # What the types describe
//!
//! The JSON umbral-rest puts on the wire, which is the model struct serialised
//! by serde. Concretely:
//!
//! - Field names stay exactly as declared. No camelCase rewrite: the wire is
//!   snake_case, and a generated type that quietly renames fields is a lie.
//! - `Option<T>` columns become `T | null`.
//! - A `ForeignKey<T>` is the target's **primary-key value**, not a nested
//!   object, so it types as `number` or `string` depending on that PK. The
//!   referenced model is named in a doc comment.
//! - `#[umbral(choices)]` columns become a string-literal union, so a typo in a
//!   status value fails at `tsc`, not in production.
//! - An `M2M<T>` field serialises as `T[]` — the full related rows when the
//!   query used `.prefetch_related(...)`, and `[]` when it didn't.
//! - `#[umbral(help = "...")]` becomes the TSDoc comment.
//!
//! # Scope
//!
//! Types only. This is the ORM's half of gaps3 #38 — the half that is true for
//! every umbral app whether or not it mounts umbral-rest. A generated *client*
//! (request functions, URL builders, and the auth/session plumbing) belongs on
//! top of umbral-openapi, which knows the routes; these types are what it would
//! import.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::migrate::{Column, ModelMeta};
use crate::orm::SqlType;

/// Emit TypeScript for every model in the live registry.
///
/// Requires `App::build()` to have run (that is what populates the registry).
/// The CLI's `typegen` subcommand boots the app for exactly this reason.
pub fn typescript() -> String {
    let mut models = crate::migrate::registered_models();
    models.sort_by(|a, b| a.name.cmp(&b.name));
    typescript_for(&models)
}

/// Emit TypeScript for an explicit model list.
///
/// Pure: no registry, no database, no I/O. `typescript()` is this function fed
/// from the registry, and the tests drive it directly.
///
/// Models are emitted in the order given. FK and M2M targets resolve against
/// this same list, so a slice holding only *some* of an app's models will type
/// a dangling FK as its fallback `number` rather than inventing a name.
pub fn typescript_for(models: &[ModelMeta]) -> String {
    let resolver = Resolver::new(models);

    let mut out = String::new();
    out.push_str(HEADER);

    // Every string-literal union, collected first so the interfaces that
    // reference them read top-down without forward declarations. TypeScript
    // hoists type aliases, but a human reading the file should not have to.
    let mut enums: BTreeMap<String, &Column> = BTreeMap::new();
    for model in models {
        for column in &model.fields {
            if let Some(name) = enum_name(model, column) {
                enums.insert(name, column);
            }
        }
    }
    if !enums.is_empty() {
        for (name, column) in &enums {
            out.push('\n');
            push_choice_docs(&mut out, column);
            let variants: Vec<String> = column
                .choices
                .iter()
                .map(|c| format!("\"{}\"", escape(c)))
                .collect();
            let _ = writeln!(out, "export type {name} = {};", variants.join(" | "));
        }
    }

    for model in models {
        out.push('\n');
        push_model_docs(&mut out, model);
        let _ = writeln!(out, "export interface {} {{", model.name);
        for column in &model.fields {
            push_field(&mut out, model, column, &resolver);
        }
        for relation in &model.m2m_relations {
            let target = resolver
                .model_name(&relation.target_table)
                .unwrap_or(&relation.target_name);
            out.push_str(
                "  /** Many-to-many. The related rows when the query used \
                 `.prefetch_related(...)`; `[]` otherwise. */\n",
            );
            let _ = writeln!(out, "  {}: {target}[];", relation.field_name);
        }
        out.push_str("}\n");
    }

    out
}

const HEADER: &str = "\
// Code generated by `umbral typegen`. DO NOT EDIT.
//
// Regenerate after any model change:
//     cargo run -- typegen --out <this file>
//
// These describe the JSON umbral puts on the wire: the model struct as serde
// serialises it. Field names are snake_case because the wire is snake_case.
// A `ForeignKey<T>` is the target's primary-key value, not a nested object.
";

/// Resolves a table name to the things a generated type needs to know about it:
/// the owning model's TypeScript name, and the type of its primary key.
struct Resolver<'a> {
    model_name: BTreeMap<&'a str, &'a str>,
    pk: BTreeMap<&'a str, (&'a str, SqlType)>,
}

impl<'a> Resolver<'a> {
    fn new(models: &'a [ModelMeta]) -> Self {
        let mut model_name = BTreeMap::new();
        let mut pk = BTreeMap::new();
        for model in models {
            model_name.insert(model.table.as_str(), model.name.as_str());
            if let Some(column) = model.pk_column() {
                pk.insert(model.table.as_str(), (column.name.as_str(), column.ty));
            }
        }
        Self { model_name, pk }
    }

    fn model_name(&self, table: &str) -> Option<&'a str> {
        self.model_name.get(table).copied()
    }

    /// The referenced model's primary-key column name. Not always `id`: a model
    /// can key on a `String` slug or a `Uuid`, and a doc comment that says "the
    /// `id` of" would be describing a column that doesn't exist.
    fn pk_name(&self, table: &str) -> Option<&'a str> {
        self.pk.get(table).map(|(name, _)| *name)
    }

    /// The type an FK column's *value* has: the referenced model's PK type.
    ///
    /// Mirrors [`crate::migrate::fk_effective_type`], but resolves against the
    /// passed model list rather than the ambient registry so this module stays
    /// pure. Falls back to `BigInt` for the same reason that function does — an
    /// unresolvable target is historically an `i64` PK.
    fn fk_value_type(&self, column: &Column) -> SqlType {
        if !matches!(column.ty, SqlType::ForeignKey) {
            return column.ty;
        }
        column
            .fk_target
            .as_deref()
            .and_then(|t| self.pk.get(t))
            .map(|(_, ty)| *ty)
            .unwrap_or(SqlType::BigInt)
    }
}

/// The union type name for a choices column, or `None` when the column has no
/// closed set.
///
/// Multichoice columns are excluded: they carry a *comma-separated subset* of
/// the choices in one string, so `"a" | "b"` would reject the legal value
/// `"a,b"`. They type as `string`, same as umbral-openapi refuses to emit an
/// `enum` for them.
fn enum_name(model: &ModelMeta, column: &Column) -> Option<String> {
    if column.choices.is_empty() || column.is_multichoice {
        return None;
    }
    Some(format!(
        "{}{}",
        model.name,
        umbral_casing::pascal_case_from_ident(&column.name)
    ))
}

fn push_field(out: &mut String, model: &ModelMeta, column: &Column, resolver: &Resolver<'_>) {
    let mut docs: Vec<String> = Vec::new();
    if !column.help.is_empty() {
        docs.push(column.help.clone());
    }
    if let Some(target) = column.fk_target.as_deref() {
        docs.push(
            match (resolver.model_name(target), resolver.pk_name(target)) {
                (Some(name), Some(pk)) => {
                    format!("Foreign key: the `{pk}` of a {name} (`{target}`).")
                }
                _ => format!("Foreign key into `{target}`."),
            },
        );
    }
    if matches!(column.ty, SqlType::Decimal) {
        docs.push(
            "Arbitrary-precision decimal, carried as a string: a JSON number \
             would lose precision."
                .to_string(),
        );
    }
    if !column.example.is_empty() {
        docs.push(format!("Example: `{}`.", column.example));
    }
    push_docs(out, &docs, "  ");

    let base = match enum_name(model, column) {
        Some(name) => name,
        None => ts_type(resolver.fk_value_type(column)),
    };
    let ty = if column.nullable {
        format!("{base} | null")
    } else {
        base
    };
    let _ = writeln!(out, "  {}: {ty};", column.name);
}

fn push_model_docs(out: &mut String, model: &ModelMeta) {
    let mut docs = Vec::new();
    if !model.display.is_empty() && model.display != model.name {
        docs.push(model.display.clone());
    }
    docs.push(format!(
        "Table `{}`, from the `{}` plugin.",
        model.table, model.app_label
    ));
    push_docs(out, &docs, "");
}

fn push_choice_docs(out: &mut String, column: &Column) {
    // Labels only carry information when they differ from the stored values.
    if column.choice_labels.len() != column.choices.len() || column.choice_labels == column.choices
    {
        return;
    }
    let pairs: Vec<String> = column
        .choices
        .iter()
        .zip(&column.choice_labels)
        .map(|(value, label)| format!("`{value}` = {label}"))
        .collect();
    push_docs(out, &[pairs.join(", ")], "");
}

/// Write a TSDoc block, or nothing when there is nothing to say. One line stays
/// on one line; more than one becomes a `*`-prefixed block.
fn push_docs(out: &mut String, lines: &[String], indent: &str) {
    let lines: Vec<&String> = lines.iter().filter(|l| !l.is_empty()).collect();
    match lines.len() {
        0 => {}
        1 => {
            let _ = writeln!(out, "{indent}/** {} */", lines[0]);
        }
        _ => {
            let _ = writeln!(out, "{indent}/**");
            for line in lines {
                let _ = writeln!(out, "{indent} * {line}");
            }
            let _ = writeln!(out, "{indent} */");
        }
    }
}

/// Map a SQL type onto the TypeScript type of its serialised form.
///
/// Deliberately agrees with `umbral-openapi`'s `openapi_type`: the two describe
/// the same bytes, and a disagreement between the OpenAPI schema and the
/// generated types would be worse than having neither.
fn ts_type(ty: SqlType) -> String {
    match ty {
        SqlType::SmallInt
        | SqlType::Integer
        | SqlType::BigInt
        | SqlType::Real
        | SqlType::Double => "number".to_string(),
        SqlType::Boolean => "boolean".to_string(),
        // Dates and times cross the wire as RFC 3339 / ISO 8601 strings, UUIDs
        // as their hyphenated form, and Decimal as a string to keep precision
        // a JSON number would drop.
        SqlType::Text
        | SqlType::Date
        | SqlType::Time
        | SqlType::Timestamptz
        | SqlType::Uuid
        | SqlType::Decimal
        | SqlType::Inet
        | SqlType::Cidr
        | SqlType::MacAddr
        | SqlType::Xml
        | SqlType::Ltree
        | SqlType::Bit
        | SqlType::FullText => "string".to_string(),
        // A JSON column holds any JSON value. `unknown` rather than `any`: the
        // consumer must narrow it before use, which is the point of generating
        // types at all.
        SqlType::Json => "unknown".to_string(),
        // umbral-rest serialises BYTEA as a JSON array of bytes, not base64.
        SqlType::Bytes => "number[]".to_string(),
        SqlType::Array(element) => format!("{}[]", ts_type(element.to_sql_type())),
        // Unreachable through `push_field`, which resolves an FK to its target's
        // PK type first. Reached only if a caller maps a raw column type; the
        // historical default PK is `i64`.
        SqlType::ForeignKey => "number".to_string(),
    }
}

/// Escape a choice value for a TypeScript double-quoted string literal.
fn escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
