//! SiteContentPlugin — generated by `umbra startapp site_content`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(site_content::SiteContentPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

pub use models::{
    BlogPost, BlogPostKind, ContactMessage, ContactStatus, ContentCategory, ContentPage,
    ContentTag, MediaAsset, NavigationItem, NavigationPlacement, PageTemplate, PublishStatus,
    SiteSetting,
};

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::web::Router;

#[derive(Debug, Default, Clone)]
pub struct SiteContentPlugin;

impl Plugin for SiteContentPlugin {
    fn name(&self) -> &'static str {
        "site_content"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![
            ModelMeta::for_::<models::ContentCategory>(),
            ModelMeta::for_::<models::ContentTag>(),
            ModelMeta::for_::<models::BlogPost>(),
            ModelMeta::for_::<models::ContentPage>(),
            ModelMeta::for_::<models::NavigationItem>(),
            ModelMeta::for_::<models::MediaAsset>(),
            ModelMeta::for_::<models::ContactMessage>(),
            ModelMeta::for_::<models::SiteSetting>(),
        ]
    }

    fn routes(&self) -> Router {
        // Add your routes here. The base path is up to you — convention
        // is `/<name>/...` for HTML and `/api/<name>/...` for JSON.
        Router::new()
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}
