//! SiteContentPlugin — generated by `umbra startapp site_content`.
//!
//! Wire this into your App by adding to `src/main.rs`:
//!
//! ```ignore
//! .plugin(site_content::SiteContentPlugin::default())
//! ```
//!
//! Declare models, routes, and `on_ready` work in the impl below.
//! See `documentation/docs/v0.0.1/plugins/the-plugin-trait.mdx` for
//! what each method does.

pub mod models;

pub use models::{
    BlogPost, BlogPostKind, ContactMessage, ContactStatus, ContentCategory, ContentPage,
    ContentTag, MediaAsset, NavigationItem, NavigationPlacement, PageTemplate, PublishStatus,
    SiteSetting,
};

use std::path::PathBuf;

use umbra::migrate::ModelMeta;
use umbra::plugin::{AppContext, Plugin, PluginError};
use umbra::templates::context;
use umbra::web::{Html, Router, StatusCode, get};

#[derive(Debug, Default, Clone)]
pub struct SiteContentPlugin;

impl Plugin for SiteContentPlugin {
    fn name(&self) -> &'static str {
        "site_content"
    }

    fn models(&self) -> Vec<ModelMeta> {
        vec![
            ModelMeta::for_::<models::ContentCategory>(),
            ModelMeta::for_::<models::ContentTag>(),
            ModelMeta::for_::<models::BlogPost>(),
            ModelMeta::for_::<models::ContentPage>(),
            ModelMeta::for_::<models::NavigationItem>(),
            ModelMeta::for_::<models::MediaAsset>(),
            ModelMeta::for_::<models::ContactMessage>(),
            ModelMeta::for_::<models::SiteSetting>(),
        ]
    }

    fn templates_dirs(&self) -> Vec<PathBuf> {
        vec![PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("templates")]
    }

    fn routes(&self) -> Router {
        Router::new().route("/docs", get(docs_page))
    }

    fn on_ready(&self, _ctx: &AppContext) -> Result<(), PluginError> {
        Ok(())
    }
}

/// The `/docs` landing page — a map into the documentation site. Static
/// editorial content (the doc topics), so no DB query.
async fn docs_page() -> Result<Html<String>, (StatusCode, String)> {
    umbra::templates::render("site_content/docs.html", &context! {})
        .map(Html)
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, e.to_string()))
}
