//! kenn — generated by `umbral startproject kenn`.
//!
//! This file is a walking tour of the umbral framework. Every surface is
//! wired in here: models + FK, migrations, auth, sessions, login_required,
//! REST with filters, admin, security, transactions, and custom error pages.
//!
//! Run with:
//!   cargo run -- migrate   # apply pending migrations (run once after checkout)
//!   cargo run -- serve     # boot the HTTP server
//!
//! Other management commands:
//!   cargo run -- makemigrations
//!   cargo run -- showmigrations
//!   cargo run -- createsuperuser

use umbral::prelude::*;
use umbral::web::{Html, Json, StatusCode, SlashRedirect};
use umbral::templates::context;
use umbral::migrate::MigrateError;
use umbral_auth::{AuthPlugin, AuthUser, login_required_html};
use umbral_sessions::SessionsPlugin;
use umbral_admin::AdminPlugin;
use umbral_rest::{RestPlugin, ResourceConfig};
use umbral_openapi::OpenApiPlugin;
use umbral_security::{SecurityConfig, SecurityPlugin};

// ---------------------------------------------------------------------------
// Models
// ---------------------------------------------------------------------------

/// A blog post. `author` is a FK to the built-in `AuthUser` model — the
/// migration engine emits `REFERENCES "auth_user"("id")` automatically.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, sqlx::FromRow, Model)]
pub struct Post {
    pub id: i64,
    pub title: String,
    pub body: String,
    pub published: bool,
    pub author: ForeignKey<AuthUser>,
    pub created_at: Option<chrono::DateTime<chrono::Utc>>,
}

// ---------------------------------------------------------------------------
// App wiring
// ---------------------------------------------------------------------------

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let settings = Settings::from_env()?;
    let pool = umbral::db::connect(&settings.database_url).await?;

    let app = App::builder()
        .settings(settings)
        .database("default", pool)

        // --- Models ----------------------------------------------------------
        // AuthUser and Session are contributed by their plugins below.
        // List your own models here.
        .model::<Post>()

        // --- Plugins ---------------------------------------------------------
        // Auth: user table, password hashing, createsuperuser command.
        .plugin(AuthPlugin::<AuthUser>::default())
        // Sessions: session table + cookie middleware.
        .plugin(SessionsPlugin::default())
        // Admin: auto CRUD UI at /admin/ for every registered model.
        .plugin(AdminPlugin::default())
        // REST: JSON CRUD + filtering at /api/<table>/.
        // The Post resource has query-string filtering enabled so
        // GET /api/post/?published=true works out of the box.
        .plugin(
            RestPlugin::default()
                .resource(ResourceConfig::new("post")),
        )
        // OpenAPI: Swagger UI at /openapi/ (override with
        // `.at("/api/docs")` if you prefer a different mount).
        .plugin(OpenApiPlugin::new())
        // Security: CSRF + hardening headers across the app. `/api`
        // is exempt so token-authenticated JSON clients can POST
        // without a browser form CSRF cookie.
        .plugin(SecurityPlugin::with_config(SecurityConfig {
            csrf_exempt_paths: vec!["/api".to_string()],
            ..Default::default()
        }))

        // --- Templates -------------------------------------------------------
        .templates_dir("templates")
        .not_found_template("404.html")
        .server_error_template("500.html")

        // Redirect /foo → /foo/  (Django-style).
        .slash_redirect(SlashRedirect::Append)

        // --- Routes ----------------------------------------------------------
        // The Routes builder records each (method, path) pair as you
        // declare it, so the dev-mode 404 panel surfaces them without
        // a parallel declaration list. Per-route middleware (here,
        // login_required_html on /dashboard) goes through the explicit
        // .route(&[methods], path, MethodRouter) form so the layer
        // attaches just to that handler — not all routes.
        .routes(
            Routes::new()
                // Public home page.
                .get("/", home)
                // API: list posts as JSON (no auth required — demo).
                .get("/api/posts", api_list_posts)
                // Dashboard: only reachable when logged in. The
                // login_required_html("/login") layer issues a 302 to
                // /login?next=/dashboard/ for anonymous visitors. The
                // .layered(method, path, mr) form takes a MethodRouter
                // so `.layer(...)` scopes to *just* this route — not
                // every route on the builder.
                .layered(
                    "GET",
                    "/dashboard",
                    get(dashboard).layer(login_required_html("/login")),
                ),
        )
        .build()?;

    // Auto-migrate on boot so `cargo run -- serve` Just Works
    // against a fresh database — but only when we're actually
    // starting the server. Running `cargo run -- makemigrations`
    // or `cargo run -- migrate` from the CLI used to silently
    // trigger `auto_migrate()` first and then report "no changes
    // detected", which made the CLI tools feel broken (IMP-1 in
    // `bugs/tests/testBugs.md`). The guard reads `std::env::args`
    // before dispatch picks them apart so it matches whatever
    // subcommand the user actually typed.
    let argv: Vec<String> = std::env::args().collect();
    let user_invoked_cli = argv.iter().skip(1).any(|a| !a.starts_with('-'));
    if !user_invoked_cli {
        auto_migrate().await?;
    }

    umbral_cli::dispatch(app).await
}

// ---------------------------------------------------------------------------
// Handlers
// ---------------------------------------------------------------------------

/// Home page. Counts published posts and renders home.html.
async fn home() -> Result<Html<String>, (StatusCode, String)> {
    let post_count = Post::objects()
        .filter(post::PUBLISHED.eq(true))
        .count()
        .await
        .map_err(internal_error)?;

    let body = umbral::templates::render(
        "home.html",
        &context!(post_count),
    )
    .map_err(internal_error)?;
    Ok(Html(body))
}

/// JSON list of all posts — demonstrates the ORM QuerySet.
async fn api_list_posts() -> Result<Json<Vec<Post>>, (StatusCode, String)> {
    let posts = Post::objects()
        .order_by(post::ID.desc())
        .fetch()
        .await
        .map_err(internal_error)?;
    Ok(Json(posts))
}

/// Dashboard: only reachable when logged in (see the `login_required_html`
/// layer in the router above). The `LoggedIn<AuthUser>` extractor supplies
/// the current user — the layer already checked the session, so this is a
/// cheap field read, not a second DB query.
async fn dashboard(
    user: umbral_auth::LoggedIn<AuthUser>,
) -> Result<Html<String>, (StatusCode, String)> {
    // Demonstrates a transaction: atomically bump a hypothetical view
    // counter and fetch the user's post list in the same transaction.
    let user_id = user.id;
    let my_posts = umbral::transaction(|tx| Box::pin(async move {
        Post::objects()
            .filter(post::AUTHOR.eq(user_id))
            .on_tx(tx)
            .fetch()
            .await
    }))
    .await
    .map_err(internal_error)?;

    let body = umbral::templates::render(
        "dashboard.html",
        &context!(user, my_posts),
    )
    .map_err(internal_error)?;
    Ok(Html(body))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn internal_error<E: std::fmt::Display>(err: E) -> (StatusCode, String) {
    (StatusCode::INTERNAL_SERVER_ERROR, err.to_string())
}

/// Run `makemigrations` + `migrate` on boot. Demo-only convenience.
async fn auto_migrate() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    match umbral::migrate::make().await {
        Ok(paths) => {
            for path in paths {
                eprintln!("auto-migrate: wrote {}",  path.display());
            }
        }
        Err(MigrateError::NoChanges) => {}
        Err(err) => return Err(Box::new(err)),
    }
    let n = umbral::migrate::run().await?;
    if n > 0 {
        eprintln!("auto-migrate: applied {n} migration(s)");
    }
    Ok(())
}
