//! build.rs for umbra-playground.
//!
//! Invokes `esbuild` and `tailwindcss` to bundle the React frontend
//! and CSS into `dist/`. Writes `OUT_DIR/generated_assets.rs` with
//! the hashed asset filenames so the runtime knows what to serve.
//!
//! If either CLI is missing, writes a degraded placeholder module
//! pointing at the static placeholder HTML. The crate still compiles.

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

const PLACEHOLDER_JS: &str = "playground.placeholder.js";
const PLACEHOLDER_CSS: &str = "playground.placeholder.css";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let frontend_dir = manifest_dir.join("frontend");
    let dist_dir = manifest_dir.join("dist");
    let out_path = out_dir.join("generated_assets.rs");

    // Rerun triggers.
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=frontend/");
    println!("cargo:rerun-if-changed=src/placeholder.html");

    fs::create_dir_all(&dist_dir).expect("create dist dir");

    let debug = env::var("PROFILE").map(|p| p == "debug").unwrap_or(true);
    let esbuild = find_in_path("esbuild");
    let tailwind = find_in_path("tailwindcss");

    let (js_name, css_name) = match (esbuild, tailwind) {
        (Some(eb), Some(tw)) => match bundle(&frontend_dir, &dist_dir, &eb, &tw, debug) {
            Ok((js, css)) => (js, css),
            Err(e) => {
                eprintln!("cargo:warning=umbra-playground: bundle failed ({e}); using placeholder");
                (PLACEHOLDER_JS.to_string(), PLACEHOLDER_CSS.to_string())
            }
        },
        _ => {
            eprintln!(
                "cargo:warning=umbra-playground: esbuild and/or tailwindcss not in $PATH; using placeholder HTML. Install with `npm i -g esbuild tailwindcss` to enable the full UI."
            );
            (PLACEHOLDER_JS.to_string(), PLACEHOLDER_CSS.to_string())
        }
    };

    let mut f = fs::File::create(&out_path).expect("create generated_assets.rs");
    writeln!(
        f,
        "// Auto-generated by build.rs. Do not edit.\n\
         pub const JS: &str = \"{js_name}\";\n\
         pub const CSS: &str = \"{css_name}\";\n"
    )
    .expect("write generated_assets.rs");
}

fn find_in_path(bin: &str) -> Option<PathBuf> {
    let path = env::var_os("PATH")?;
    for dir in env::split_paths(&path) {
        let full = dir.join(bin);
        if full.is_file() {
            return Some(full);
        }
    }
    None
}

fn bundle(
    frontend_dir: &Path,
    dist_dir: &Path,
    esbuild: &Path,
    tailwind: &Path,
    debug: bool,
) -> Result<(String, String), String> {
    let entry = frontend_dir.join("index.tsx");
    let css_entry = frontend_dir.join("styles/app.css");
    let tailwind_config = frontend_dir.join("styles/tailwind.config.js");

    let mut js_args: Vec<String> = vec![
        entry.to_string_lossy().into_owned(),
        "--bundle".into(),
        "--loader:.tsx=tsx".into(),
        "--outfile=playground.tmp.js".into(),
    ];
    if debug {
        js_args.push("--sourcemap".into());
    } else {
        js_args.push("--minify".into());
        js_args.push("--sourcemap=inline".into());
        js_args.push("--define:process.env.NODE_ENV=\"production\"".into());
    }

    let status = Command::new(esbuild)
        .args(&js_args)
        .current_dir(dist_dir)
        .status()
        .map_err(|e| format!("esbuild: {e}"))?;
    if !status.success() {
        return Err("esbuild exited non-zero".into());
    }

    let mut css_args: Vec<String> = vec![
        format!("-c={}", tailwind_config.display()),
        format!("-i={}", css_entry.display()),
        "-o=playground.tmp.css".into(),
    ];
    if !debug {
        css_args.push("--minify".into());
    }

    let status = Command::new(tailwind)
        .args(&css_args)
        .current_dir(dist_dir)
        .status()
        .map_err(|e| format!("tailwindcss: {e}"))?;
    if !status.success() {
        return Err("tailwindcss exited non-zero".into());
    }

    let js_hash = short_hash(dist_dir.join("playground.tmp.js"));
    let css_hash = short_hash(dist_dir.join("playground.tmp.css"));

    let js_final = format!("playground.{js_hash}.js");
    let css_final = format!("playground.{css_hash}.css");
    fs::rename(dist_dir.join("playground.tmp.js"), dist_dir.join(&js_final))
        .map_err(|e| format!("rename js: {e}"))?;
    fs::rename(
        dist_dir.join("playground.tmp.css"),
        dist_dir.join(&css_final),
    )
    .map_err(|e| format!("rename css: {e}"))?;

    Ok((js_final, css_final))
}

fn short_hash(path: PathBuf) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};

    let bytes = fs::read(&path).unwrap_or_default();
    let mut h = DefaultHasher::new();
    bytes.hash(&mut h);
    let n = h.finish();
    format!("{n:016x}")
}
