//! build.rs for umbra-playground.
//!
//! Runs `npm run build` inside `frontend/` to produce the Vite bundle,
//! then copies `frontend/dist/` into the crate's `dist/` and writes
//! `OUT_DIR/generated_assets.rs` with the hashed JS + CSS filenames.
//! The runtime's `shell.html` template uses those filenames to load
//! the right bundle at request time.
//!
//! Degrades gracefully when:
//!   - `npm` is not in $PATH (no Node installed),
//!   - `frontend/node_modules/` is missing (user hasn't run
//!     `npm install` yet),
//!   - `npm run build` exits non-zero, or
//!   - Vite produces no `index-*.js` / `index-*.css` in
//!     `frontend/dist/assets/`.
//!
//! In each case we fall back to `playground.placeholder.{js,css}` so
//! the crate still compiles and the runtime can serve the placeholder
//! HTML telling the user how to enable the full UI.

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;

const PLACEHOLDER_JS: &str = "playground.placeholder.js";
const PLACEHOLDER_CSS: &str = "playground.placeholder.css";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let frontend_dir = manifest_dir.join("frontend");
    let frontend_dist = frontend_dir.join("dist");
    let crate_dist = manifest_dir.join("dist");
    let out_path = out_dir.join("generated_assets.rs");

    // Rerun triggers. We rerun on every source change inside frontend/
    // EXCEPT the dist/ and node_modules/ subdirs (which we ourselves
    // would write into and that would cause an infinite rerun loop).
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=frontend/src");
    println!("cargo:rerun-if-changed=frontend/index.html");
    println!("cargo:rerun-if-changed=frontend/package.json");
    println!("cargo:rerun-if-changed=frontend/vite.config.ts");
    println!("cargo:rerun-if-changed=frontend/tsconfig.json");
    println!("cargo:rerun-if-changed=src/placeholder.html");
    println!("cargo:rerun-if-changed=src/shell.html");

    fs::create_dir_all(&crate_dist).expect("create dist dir");
    // Guarantee dist/assets/ exists so the static pipeline (which
    // serves files off `<crate>/dist/` at runtime via the `playground`
    // namespace registered in `Plugin::static_dirs`) always has a
    // directory to resolve against. On a fresh checkout with no vite
    // output yet this keeps the source dir present (empty) rather than
    // missing.
    let assets_subdir = crate_dist.join("assets");
    fs::create_dir_all(&assets_subdir).expect("create dist/assets dir");

    let (js_name, css_name) = match bundle_with_vite(&frontend_dir, &frontend_dist, &crate_dist) {
        Ok(pair) => pair,
        Err(e) => {
            eprintln!("cargo:warning=umbra-playground: {e}; serving placeholder");
            // In placeholder mode `dist/assets/` will be empty —
            // include_dir embeds an empty tree, the runtime serves
            // the placeholder HTML for the shell route, and any
            // request for an asset 404s. That's the expected
            // degraded behaviour.
            (PLACEHOLDER_JS.to_string(), PLACEHOLDER_CSS.to_string())
        }
    };

    let mut f = fs::File::create(&out_path).expect("create generated_assets.rs");
    writeln!(
        f,
        "// Auto-generated by build.rs. Do not edit.\n\
         pub const JS: &str = \"{js_name}\";\n\
         pub const CSS: &str = \"{css_name}\";\n"
    )
    .expect("write generated_assets.rs");
}

fn find_in_path(bin: &str) -> Option<PathBuf> {
    let path = env::var_os("PATH")?;
    let names: &[&str] = if cfg!(windows) {
        &[".cmd", ".exe", ""]
    } else {
        &[""]
    };
    for dir in env::split_paths(&path) {
        for suffix in names {
            let full = dir.join(format!("{bin}{suffix}"));
            if full.is_file() {
                return Some(full);
            }
        }
    }
    None
}

fn bundle_with_vite(
    frontend_dir: &Path,
    frontend_dist: &Path,
    crate_dist: &Path,
) -> Result<(String, String), String> {
    let npm = find_in_path("npm").ok_or_else(|| {
        "npm not in $PATH — install Node.js + npm (https://nodejs.org), \
         then re-run `cargo build` to bundle the React playground"
            .to_string()
    })?;
    let node_modules = frontend_dir.join("node_modules");
    if !node_modules.exists() {
        return Err(format!(
            "frontend/node_modules missing — run `cd {} && npm install` once, \
             then re-run `cargo build`",
            frontend_dir.display()
        ));
    }

    let status = Command::new(&npm)
        .args(["run", "build"])
        .current_dir(frontend_dir)
        .status()
        .map_err(|e| format!("npm run build failed to spawn: {e}"))?;
    if !status.success() {
        return Err("npm run build exited non-zero — fix the vite errors above".into());
    }

    let assets_dir = frontend_dist.join("assets");
    let mut js_name: Option<String> = None;
    let mut css_name: Option<String> = None;
    for entry in fs::read_dir(&assets_dir)
        .map_err(|e| format!("can't read {}: {e}", assets_dir.display()))?
    {
        let entry = entry.map_err(|e| e.to_string())?;
        let name = entry.file_name().to_string_lossy().into_owned();
        // Vite emits `index-<hash>.js` and `index-<hash>.css` for the
        // entry chunk by default. Fonts and other assets keep their
        // own prefixes (inter-*.woff2, etc.) so they don't shadow the
        // entry chunk match.
        if name.starts_with("index-") && name.ends_with(".js") {
            js_name = Some(name);
        } else if name.starts_with("index-") && name.ends_with(".css") {
            css_name = Some(name);
        }
    }
    let js_name = js_name.ok_or_else(|| {
        format!(
            "no index-*.js in vite output at {} — \
             frontend likely renamed; check vite.config.ts entry name",
            assets_dir.display()
        )
    })?;
    let css_name = css_name.ok_or_else(|| {
        format!(
            "no index-*.css in vite output at {} — \
             frontend likely emits no CSS chunk; check the entry @import lines",
            assets_dir.display()
        )
    })?;

    // Wipe the crate's dist/ before mirroring the fresh vite output —
    // otherwise each build's hashed filenames accumulate alongside the
    // last build's, and the directory grows unbounded across iteration.
    // We only delete *contents* (not the directory itself) so any
    // outer process holding the path open isn't disturbed.
    if let Ok(read) = fs::read_dir(crate_dist) {
        for entry in read.flatten() {
            let p = entry.path();
            let _ = if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
                fs::remove_dir_all(&p)
            } else {
                fs::remove_file(&p)
            };
        }
    }

    // Mirror the full vite dist/ into the crate's dist/ so the runtime
    // (which serves from <crate>/dist/) sees both the entry bundles
    // and the font files referenced from the CSS.
    copy_dir_recursive(frontend_dist, crate_dist)
        .map_err(|e| format!("can't copy vite dist into crate dist: {e}"))?;

    Ok((js_name, css_name))
}

fn copy_dir_recursive(src: &Path, dst: &Path) -> std::io::Result<()> {
    if !src.is_dir() {
        return Ok(());
    }
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let target = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_recursive(&entry.path(), &target)?;
        } else if ty.is_file() {
            // Replace existing files unconditionally — incremental
            // builds keep the freshest copy.
            if target.exists() {
                let _ = fs::remove_file(&target);
            }
            fs::copy(entry.path(), &target)?;
        }
    }
    Ok(())
}
